### ISSUE TITLE
"Remove Space Below The Image" Options Doesn't Work

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#466] opened 2016-09-14 19:57 UTC
This option, found in the Image Module settings, does not work in the Visual Builder.

**Comment by fikrirasyid** [comment] 2016-09-15 00:46
@timayhelen can you take a look at it again? This seems to be duplicate of https://github.com/elegantthemes/Divi-Beta/issues/451 which has been merged into `master`. I've  rechecked it on the `master` and it works as expected:

![image module - remove space at bottom](https://cloud.githubusercontent.com/assets/916442/18534712/67545bb8-7b18-11e6-985d-5f63a0b023f1.jpg)

![image-no-space](https://cloud.githubusercontent.com/assets/916442/18534721/7c8eae20-7b18-11e6-8e9b-c1c4c19ab724.gif)

**Comment by timayhelen** [comment] 2016-09-15 02:19
@fikrirasyid This feature actually applies negative margin in order to force the image to sit at the bottom of the section. Here is the difference between the Visual Builder and the front-end:

![screen shot 2016-09-14 at 7 18 41 pm](https://cloud.githubusercontent.com/assets/3333028/18536207/155252a6-7ab0-11e6-9e14-74ce2d7521dc.png)

![screen shot 2016-09-14 at 7 18 46 pm](https://cloud.githubusercontent.com/assets/3333028/18536208/186dad64-7ab0-11e6-9259-315d4b8e64b9.png)

**Comment by fikrirasyid** [comment] 2016-09-15 11:13
@timayhelen thanks for clarifying it. I've successfully replicate the issue. A patch for the issue has been submitted at https://github.com/elegantthemes/submodule-builder/pull/1185

**Closed** 2016-09-16 16:26 UTC
Labels: BUG, DESIGN SIGNOFF, READY FOR REVIEW
