### ISSUE TITLE
Visual Builder :: Row settings panel overlaps Text Module content

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#434] opened 2016-09-10 07:30 UTC
### Problem:
![image](https://cloud.githubusercontent.com/assets/20072036/18408756/3039cff8-7741-11e6-9d9d-21fa8bfa477e.png)

### Steps To Reproduce:
1. Add Text Module into the first row 
2. Add text
3. When you try to select some text the row settings panel will overlap this text and no way to see what you selecting.

**Comment by lots0logs** [comment] 2016-09-12 15:37
@dm-chechik Could you confirm that this issue still exists with the latest version?

**Comment by dm-chechik** [comment] 2016-09-12 16:15
@lots0logs Yeah, still there
![image](https://cloud.githubusercontent.com/assets/20072036/18443352/3b74ed2a-791d-11e6-80a2-b55e3d81f502.png)

**Comment by lots0logs** [comment] 2016-09-12 16:38
@dm-chechik Did you try clicking inside the text first to activate inline editing? It should move out of the way once you click inside the text. It does for me. Make sure you are using the latest version. Let me know. Thanks!

**Comment by dm-chechik** [comment] 2016-09-12 16:44
@lots0logs If I click inside the text I see the inline editor panel, but the row panel still prevents me to select the start of the text. (I can select text but I don't see what I selected exactly)

**Comment by lots0logs** [comment] 2016-09-12 18:17
Duplicate of #431

**Closed by lots0logs** 2016-09-12 18:17 UTC
Labels: QUESTION
