### ISSUE TITLE
Theme customizer :: mobile styles :: section/row height

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#554] opened 2016-09-28 06:45 UTC
### Problem:

VB responsive preview shows the default padding instead of custom padding that you set in theme customizer > mobile style.

### Steps To Reproduce:
1. Change row and section height to 0px in theme customizer > mobile styles
2. Open mobile preview in VB
![screenshot_2](https://cloud.githubusercontent.com/assets/9657712/18903257/dd5fb184-8579-11e6-8bb2-e01441c4f0c8.png)

**Comment by lots0logs** [comment] 2016-10-05 16:41
@SlavaET It looks like these changes cause custom values input directly into modules to not be applied in the VB (the theme customizer styles are overriding the individual module styles).

**Comment by SlavaET** [comment] 2016-10-05 16:42
@lots0logs can you please explain which exactly styles? I tested it with some and it worked fine.

**Comment by lots0logs** [comment] 2016-10-05 17:48
@SlavaET It was the padding (top and bottom) of Rows. Sorry, I didnt mention that before. I didnt think it would be only affecting that style, so I figured it would be easy to notice :sweat_smile:

**Comment by SlavaET** [comment] 2016-10-06 06:29
Fixed. 
@lots0logs I added new PR for the submodule-builder - https://github.com/elegantthemes/submodule-builder/issues/1283
So make sure `Divi` and `submodule-builder` are both on correct branches during your test.

**Comment by lots0logs** [comment] 2016-10-06 18:58
@SlavaET I found some more issues that we should take care of in this PR. I will post the details with annotated screenshots in about an hour....

**Comment by lots0logs** [comment] 2016-10-06 20:35
I set all the values in ***Theme Customizer>>Mobile Styles*** to obscenely large values and then I checked the Homepage Extended Layout in the VB. Here's what I found: 

The slider's and CTA's don't use the correct values when the builder loads. If you change the value in the module settings it works fine. Then if you reset the value back to default in the settings it takes the correct default value that it should have had in the beginning.

![screencapture-et-falgout-us-divi-554-fix-row-responsive-padding-conflict-1475778000118](https://cloud.githubusercontent.com/assets/4675662/19169515/7e507536-8bda-11e6-8113-8b741028bff4.png)

**Comment by SlavaET** [comment] 2016-10-07 04:58
@lots0logs you can see exactly the same results on Front-end, so it's not the Visual Builder specific issue.
I'll take a look at this issue anyway.

**Comment by SlavaET** [comment] 2016-10-07 06:32
@lots0logs fixed the issue with Slider Font size option. It works as expected now in the VB and on the Front-end.
As for the section height issue on your screenshot - that option is not applied to FW sections and this behaviour is intentional since there is a code which sets the padding of FW sections to 0 when custom section height is defined.
As for the CTA I'm not sure that understand which option doesn't work there. We have specific section in Customizer to adjust the CTA settings ( `Customizing > Buttons > Buttons Style` ) and these options work as expected though there is no mobile settings.

**Comment by SlavaET** [comment] 2016-10-07 06:50
Also found and fixed one more issue - body styles defined in Customizer were applied to the VB interface and it broke the appearance of module settings modal ( probably some other areas as well ).

**Comment by lots0logs** [comment] 2016-10-07 16:20
@SlavaET It looks like the Tablet Styles (***Theme Customizer>>Mobile Styles>>Tablet***) now get applied to the mobile view as well (both in the VB and on the page itself)..

**Comment by SlavaET** [comment] 2016-10-09 06:06
@lots0logs isn't it expected behaviour? If you define styles for tablet, then it applied to `max-width: 980px` so it'll be applied for the phone screens as well unless you define different styles for the phone breakpoint which will override the tablet styles.

**Comment by lots0logs** [comment] 2016-10-09 08:24
@SlavaET Code-wise, yes, it is indeed the expected behavior (it hadn't occurred to me the other day :sweat_smile: ). Though from a UI perspective, I think its expected that mobile values affect mobile and tablet values affect tablet. Most of our customer's don't even know CSS, so this behavior probably doesn't  make sense to them (so they'll either post a ticket in the forum or they will write it off as Divi being "buggy"). That being said, I don't think this is something we can change at this point (as it would break backwards-compatibility), so we're kind of stuck with it :frowning_face:

**Closed** 2016-10-12 23:31 UTC
Labels: BUG, DESIGN SIGNOFF, QUALITY ASSURED, READY FOR REVIEW
