### ISSUE TITLE
VB :: Bar Counter :: Does Not Work 

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#1040] opened 2017-02-24 20:50 UTC
### Problem:

Bar Counter Does not work at all if you define no values when you first create the module. 

### Steps To Reproduce:
1.  Switch to VB and create Bar Counter module with some tabs and no values anywhere.
2. Switch to BB, wait for the Sync process.
3. Open Bar Counter settings and close it right away w/o adding any changes.
4. Switch back to VB. Now you can see the Bar's background is changed to Blue color and no way what value you define under the settings it does now work.

Screen cast;
http://youtu.be/zhjf-fRpTnI?hd=1

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1803

**Comment by lots0logs** [comment] 2017-02-28 19:23
@SlavaET Following the steps to reproduce provided by @kary4 I'm seeing the following error in the browser console:

Uploading images on github is down soooo Dropbox to the rescue :smiley: 

https://www.dropbox.com/s/eljd7px9ze984y3/2017-02-28_01-20-54-PM.png?dl=0

**Comment by Jronk** [comment] 2017-03-01 00:27
Errors fixed

**Comment by lots0logs** [comment] 2017-03-01 00:54
@Jronk When you move the module to another place in the layout (in VB) it clears the values (the percentages)

**Comment by Jronk** [comment] 2017-03-02 00:38
@lots0logs fixed the drag bug 😌

**Comment by lots0logs** [comment] 2017-03-02 01:12
@Jronk After following the steps to reproduce this issue, any bar counter children modules that you created quit responding to settings changes in the VB. However if you add new children they work just fine (until you switch to the BB and back again).

**Comment by Jronk** [comment] 2017-03-02 02:04
https://github.com/elegantthemes/submodule-builder/pull/1791 was merged as it successfully fixed https://github.com/elegantthemes/Divi-Beta/issues/1041. A new PR needs to be created to fix this issue.

**Comment by SlavaET** [comment] 2017-03-02 08:03
Found the root cause finally.

**Closed** 2017-03-04 00:15 UTC
Labels: !IMPORTANT, BUG, DESIGN SIGNOFF, QUALITY ASSURED, READY FOR REVIEW
