### ISSUE TITLE
Simply refreshing without changing produces browser autosave

### ISSUE THREAD

**Issue by Jronk** [elegantthemes/Divi-Beta#1009] opened 2017-02-23 19:34 UTC
### Problem:

Originally from: https://github.com/elegantthemes/Divi-Beta/issues/1001#issuecomment-281842201
> in the processes of switching between the VB and BB, even when no edits are made, browser backups are initiated by WP in the BB. So even just by opening the BB and VB, once you refresh the page you will get a browser backup notification even though nothing was changed. Something is being changed in the process of syncing nothing.

**Comment by Jronk** [comment] 2017-02-23 19:58
But, I am not able to reproduce (at least any more)... It could be that its been solved in the latest fixes. Also, this could be fixed via: https://github.com/elegantthemes/submodule-builder/pull/1766

**Comment by lots0logs** [comment] 2017-02-23 20:00
I cannot reproduce now either.

**Comment by timayhelen** [comment] 2017-02-23 20:14
Ok, closing for now. I am doing another round of testing and will open new issues if I find anything else.

**Closed by timayhelen** 2017-02-23 20:14 UTC
Labels: BUG, BUILDER SYNC, QUESTION
