### ISSUE TITLE
Possible Issue With Jetpack When User Connected To WP.com Account

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#592] opened 2016-10-06 15:47 UTC
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=595472

**Comment by SlavaET** [comment] 2016-10-26 10:46
I think we can close this one since this issue was not confirmed and it's the only one ticket ( as far as I see ) with this issue.
I contacted @FaycalBoutam - he was not able to reproduce it and customer didn't reply for a long time.

**Closed** 2016-10-26 16:46 UTC
Labels: BUG
