### ISSUE TITLE
Child Modules Are Not Synced When Multiple Instances Of Global Modules Are Synced In VB

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#1095] opened 2017-03-15 06:49 UTC
### Problem:
This applies to Slides, Tabs, etc.. Only applies to what is shown in the VB. What is actually synced on the server is correct.

### Steps To Reproduce
1. Add two instances of a global slider module to the page.
2. In one of the instances, change some advanced design settings for the first slide (like font styles for example). 
3. Save and close the settings modal.
4. You will see the changes do not appear on the other global module instance.

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1835

Note: In summary, the issue that was being mentioned above can't be replicated but I did found several issues regarding inline editor on global submodule. See https://github.com/elegantthemes/Divi-Beta/issues/1095#issuecomment-286949350 below

**Comment by fikrirasyid** [comment] 2017-03-16 00:10
@lots0logs can you take a screencast on how the issue occurs? I've been trying to replicate the issue but it appears ok to me:

![1095-clarification](https://cloud.githubusercontent.com/assets/916442/23976030/5e2aa7ac-0a17-11e7-8c15-4454b2f2cdbe.gif)

In general, every option that is synced by closing settings modal work as expected so far. The only issue that I can found within child module and global sync is that in some module, inline text block editing doesn't work:

![1095-clarification-2](https://cloud.githubusercontent.com/assets/916442/23976057/938736d6-0a17-11e7-8e76-bae3976c60c6.gif)

**Comment by fikrirasyid** [comment] 2017-03-16 03:40
I checked every module which has sub-module, and the anomalies that I can confirm are as follow:

***

Issues list

# Accordion
- [ ] Inline accordion item title

# Bar Counters	
- [ ] Update added via bar item's inline editor doesn't updated into settings modal
- [ ] Inline bar item label
- [ ] Inline bar value

# Contact Form
> works as intended

# Pricing Table
- [ ] inline title editor
- [ ] inline subtitle editor
- [ ] inline currency editor
- [ ] inline price editor
- [ ] Inline frequency editor
- [ ] Inline content editor

# Slider
- [ ] Inline slide title
- [ ] Inline slide content

# Tabs
- [ ] Inline tab nav 
- [ ] Inline tab content

# Video Slider
> works as intended

# FW slider
> works as intended

**Comment by fikrirasyid** [comment] 2017-03-16 14:11
Cc-ing @timayhelen. This issue is pretty significant since it is caused by shortcode trimming.

**Comment by lots0logs** [comment] 2017-03-16 20:01
@fikrirasyid I noticed that after making a change using the inline editor its not showing the spinner to indicate the other module is being updated. I think the delay is significant enough to warrant showing the spinner :thinking:

**Comment by fikrirasyid** [comment] 2017-03-17 00:50
@lots0logs regarding this:

>  I noticed that after making a change using the inline editor its not showing the spinner to indicate the other module is being updated. I think the delay is significant enough to warrant showing the spinner 🤔

I thought this was by design. Let me check that again.

> Issue when *selective sync is being used to sync certain tabs*: Save *Blurb Module* as global and exclude the General tab from syncing.

How about open new issue for this? this appears to be not submodule / child module specific issue. I think it'd be better to avoid compounding issues in one ticket

**Comment by lots0logs** [comment] 2017-03-17 01:06
@fikrirasyid Err..I don't know why my fingers typed "Blurb" when my brain was saying "Slider"  :sweat_smile:

**Comment by fikrirasyid** [comment] 2017-03-17 01:20
@lots0logs have you tried it on `1095-divi-beta`? It'd be helpful if you can get a screencast of it. I've tried to replicate it on `1095-divi-beta` but it works as expected 🤔

**Comment by fikrirasyid** [comment] 2017-03-17 03:35
@lots0logs I've pushed a commit that fixes spinnerless situation when editable-block modifies global module's settings / attributes. This turns out to be caused by https://github.com/elegantthemes/submodule-builder/pull/1778/commits/d2e56bb57411a05266bcf39c64d9547da4e1e160#diff-3d118346b9153b174ee444572afed18dR3822 of https://github.com/elegantthemes/submodule-builder/pull/1778. Can you check it out and see whether the issue on https://github.com/elegantthemes/submodule-builder/pull/1778 reappearing or not? It turns out that https://github.com/elegantthemes/submodule-builder/pull/1778 was your PR 😅 I've checked it and  it doesn't seem to cause any issue to reappear, but it'd be better to be safe.

I've posted the details of the issue on https://github.com/elegantthemes/submodule-builder/commit/3d990d541f65795fc62a2aae3f8d316b37277496

As in the following:

> Issue when selective sync is being used to sync certain tabs:
> 1. Save Blurb Module as global and exclude the General tab from syncing.
> 2. Duplicate the module.
> 3. Change the heading text on the duplicate.
> 4. You'll see that the original instance loses its heading text.

This appears to be fixed on `1095-divi-beta`. Can you take a look at it?

**Closed** 2017-03-20 22:37 UTC
Labels: !IMPORTANT, BUG, DESIGN SIGNOFF, QUALITY ASSURED, READY FOR REVIEW
