### ISSUE TITLE
Pre-made Layouts not working - loading " Creative Agency" creates never ending spin screen for VE

### ISSUE THREAD

**Issue by elephantik** [elegantthemes/Divi-Beta#169] opened 2016-08-23 15:47 UTC
### Problem:

Dear Divi Dev team, 

I have encountered a bug using your pre-made layouts if you select "Creative Agency" as a pre-made layout and populate your page and publish it and than later try to use Visual Editor it spins and spins and spins. Only until I cleared the entire page layout was it able to load.

UPDATE *** I removed the module "PORTFOLIO" From Creative Agency's premade layout. That was the isolated module that was causing the page to spin spin spin in the white screen for Visual Editor.

### Steps To Reproduce:
1.  Load up a fresh install of Divi Beta
2. Create a Page and select a Divi pre-selected layout from the provided library
3. Select 'Creative Agency' layout, and publish
4. Click Visual Editor... It goes to spin and spin and spin white screen.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:
OS 10.9 

**Browser**:
Chrome Latest version
Version 52.0.2743.116 (64-bit)

**Screen Resolution**:
2560x1440

**Screenshot or Screencast**:
https://www.dropbox.com/sh/yjvdpsvkhoswgsi/AAAHUDhp-q7a7rNag8c-Jtwya?dl=0 
Before and after pictures in here. 

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formatted the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by jamesrayth** [comment] 2016-08-23 16:16
The white page issue is usually caused by conflicting plugins. I had this same issue with Yoast, they patched it in the lastest patch (released yesterday) but it also errors out with Jetpack Publish and Share modules. 
Disable all of your plugins except ET plugins and then try it, then reactivate plugins until it stops working and let them know which plugin broke it.

**Comment by elephantik** [comment] 2016-08-23 16:23
The plugins I have installed are just the install plugins for Divi and Divi Builder and Divi Child themes. This did not obstruct this load. What obstructed this load was the Portfolio Module.

**Comment by jamesrayth** [comment] 2016-08-23 16:23
I thought this was the blank page issue caused by plugins, but following the repro steps I see the same thing described, the loading visual builder animation. There is this showing in the dev console:

(4) bundle.js:10 Uncaught TypeError: Cannot read property '__reactInternalInstance$hci9zf4of0khy2spyxdt5ipb9' of null     bundle.js:10

**Comment by elephantik** [comment] 2016-08-23 16:31
Yay we caught a bug.

**Comment by fikrirasyid** [comment] 2016-08-24 03:47
@elephantik @jamesrayth thank you for reporting this bug! Can you inform me the following information:

- How many portfolio item you have on your installation?
- How many portfolio categories and tags you have?

I'm still trying to replicate the issue (no luck *yet* so far). It probably has something to do with saved portfolio data.

**Comment by jamesrayth** [comment] 2016-08-24 03:49
@fikrirasyid I have no portfolio items and no portfolio tags.

**Comment by fikrirasyid** [comment] 2016-08-24 03:49
@jamesrayth thank you for confirming it 👍

**Comment by fikrirasyid** [comment] 2016-08-24 04:11
@elephantik @jamesrayth a patch for this issue has been added and currently under review. Once it passes the review, it should be merged on the next beta release. Thank you for reporting this bug.

**Closed** 2016-08-24 23:58 UTC
Labels: BUG, DESIGN SIGNOFF, READY FOR REVIEW
