### ISSUE TITLE
VB :: Map : Map doesn't update when a new item is added

### ISSUE THREAD

**Issue by VladET** [elegantthemes/Divi-Beta#771] opened 2016-11-17 11:03 UTC
### Problem:

The new item pin will not show up unless you change a setting to force the map to update, so it seems that the map is not updated when the item is added. When you delete the item, the map does get updated. 

Screencast: http://screencast-o-matic.com/watch/cDXb6PQV0O

**Edit:** The map in the modal updates when the item is added, the map in preview doesn't.
When you delete the item, it updates in the preview map but not in the modal.

http://screencast-o-matic.com/watch/cDXbX6QV0L

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1465

**Comment by lots0logs** [comment] 2016-11-29 02:28
@SlavaET Can we prevent the map from "flashing" when its re-rendered? 

![2016-11-28 20-27](https://cloud.githubusercontent.com/assets/4675662/20694195/338f50b4-b5a9-11e6-85bd-1ba6352f17ee.gif)

**Comment by SlavaET** [comment] 2016-11-30 06:17
@lots0logs fixed.

**Comment by lots0logs** [comment] 2016-12-01 03:21
@SlavaET Still seeing flashing the first time the module is hovered after page loads as well as the first time the settings modal is snapped. Also, notice what happens when unsnapping the modal. 

![2016-11-30 21-18](https://cloud.githubusercontent.com/assets/4675662/20780728/ec586dac-b742-11e6-936a-f1baee03e3ce.gif)

**Comment by SlavaET** [comment] 2016-12-01 03:50
@lots0logs this flashing happens when map is reinitiated. We need it to update the map in some cases, so we cannot fully get rid of that flashing effect. We only reinit the map when it's required.

**Comment by lots0logs** [comment] 2016-12-01 04:00
@SlavaET Its not required to reinit the map the first time it is hovered, is it? :stuck_out_tongue_winking_eye:  Obviously we need to do it for modal snap because the size of the viewport changes. Though we should make sure that the entire map re-renders properly (and not with a blank space on the right side).

**Comment by SlavaET** [comment] 2016-12-01 13:00
@lots0logs I cannot reproduce the issue with reinit on hover. 
Fixed the issue with map reinit on snap, please clear cache of your browser and check the latest version of branch. 
Let me know if you still see the issue with map reinit on hover.

**Comment by lots0logs** [comment] 2016-12-01 19:31
@SlavaET Yeah, the flashing the first time its hovered is still happening for me. Also looks like it reinits twice when snapping the modal (only the first time as well..coincidence? :thinking: )

![2016-12-01 13-30](https://cloud.githubusercontent.com/assets/4675662/20809058/72a47d38-b7ca-11e6-933e-be679959ee2b.gif)

**Comment by SlavaET** [comment] 2016-12-02 04:34
@lots0logs this is weird. I cannot reproduce this flash on hover, which browser do you use? Maybe you have some plugins/extensions which trigger the `resize` event and it triggers the Map reinit?
![no-map-flash](https://cloud.githubusercontent.com/assets/3446682/20822997/31b739ae-b87a-11e6-9028-a76fbcf058de.gif)

Fixed the issue with extra reinit on first snap
Also found and fixed following issues:
- fixed some js errors which I found during the testing;
- fixed the issue when map was not re-centered on window resize;
- fixed the issue when map was not updated on modal settings close ( in snap mode ).

**Comment by lots0logs** [comment] 2016-12-03 02:23
@SlavaET I'm still seeing the flash upon first hover. I use Chrome, but I just checked with Firefox and got the same result. Here is the page I am using to test this PR. Could you check it and see if you can reproduce the flash issue? 

http://et.falgout.us/divi/771-fix-map-module-update-vb/

**Comment by SlavaET** [comment] 2016-12-05 05:43
@lots0logs I cannot load the VB on your website because of this - https://github.com/elegantthemes/Divi-Beta/issues/778#issuecomment-261502307
And I cannot edit theme files to overcome the issue, it says "Error" when I'm trying to save the files on your server via WPIDE. But I was able to edit files a few days ago.. 🤔

**Comment by lots0logs** [comment] 2016-12-05 10:19
@SlavaET Okay, I'm going to reset the branches and fixup the file permissions right now. Then I won't touch it again for at least the next 4-5 hours. Hopefully that will give you time to check it :smiley:

**Comment by SlavaET** [comment] 2016-12-09 09:56
@lots0logs please ping me on Slack when you'll be online, so we can coordinate the testing of this issue.
I merged the latest master into this PR, so I'll be able to load the VB on your server and check 😄

**Comment by SlavaET** [comment] 2016-12-29 09:42
@lots0logs I merged the latest master into my PR, can you please check it again? If you still see the issue - let me know and let me test it on your server, because I cannot reproduce the issue on my localhost..

**Comment by lots0logs** [comment] 2017-01-05 18:59
@SlavaET I have good news and bad news. The good news is that flash is gone. The bad news is I noticed something I missed before :sweat_smile:  When you edit the address of an existing map point the map doesn't update.

**Comment by SlavaET** [comment] 2017-01-06 04:38
@lots0logs I merged the latest master into my PR and I cannot reproduce the issue you described. Can you please check it again and if you still can reproduce, then please post the exact steps.

**Comment by timayhelen** [comment] 2017-01-09 21:55
@SlavaET I think we need to add a debounce to the Map Pin Address field and Title field in the Pin Settings. Right now it re-renders the map with every keystroke, which is quite distracting while typing in the information. 
![map](https://cloud.githubusercontent.com/assets/3333028/21785156/3845f6fe-d673-11e6-87d7-479694a1ccb4.gif)

**Comment by SlavaET** [comment] 2017-01-18 06:41
@timayhelen I added 1 second debounce for the map reinit. It seems to be the most comfortable delay. Does it work fine for you?

**Comment by timayhelen** [comment] 2017-01-18 21:08
@SlavaET Now new pins are not appearing for me on the map. Does it work for you?

**Comment by SlavaET** [comment] 2017-01-19 04:11
@timayhelen yes, it works for me. I merged the latest master into my PR, can you please check again just in case?. Also, do you see any errors in console when this issue occurs?
And, where do you see the issue - on the real Map on page or on the Map preview in Settings Modal?

**Comment by Jronk** [comment] 2017-01-20 00:18
@SlavaET please see PR review: https://github.com/elegantthemes/submodule-builder/pull/1465#pullrequestreview-17586958

**Comment by SlavaET** [comment] 2017-01-20 04:38
@Jronk fixed.

**Comment by Jronk** [comment] 2017-01-21 01:56
@SlavaET please see PR review (more...) :) https://github.com/elegantthemes/submodule-builder/pull/1465#pullrequestreview-17796084

**Comment by SlavaET** [comment] 2017-01-23 03:54
@Jronk done.

**Closed** 2017-03-10 23:49 UTC
Labels: BUG, DESIGN SIGNOFF, QUALITY ASSURED, READY FOR REVIEW
