### ISSUE TITLE
BlueHost :: Auto Saves :: Can't publish a page with VB

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#953] opened 2017-02-09 12:28 UTC
### Problem:

Possibly related to: https://github.com/elegantthemes/Divi-Beta/issues/929
I can't publish the page with VB and I'm seeing the "An Autosave Exists" popup.

![93](https://cloud.githubusercontent.com/assets/16414613/22783140/6d4a278c-eec2-11e6-894f-e2ffda2c044d.gif)

**Comment by FaycalBoutam** [comment] 2017-02-10 18:05
Actually the page is published, and I can click the "Exit Visual Builder" link. It's just not working when you try the link in the BB as seen in the above screen.

**Comment by kary4** [comment] 2017-02-12 21:38
This happens only if you Preview Page in a new Tab and then click Enable VB. If you preview the page in the same tab and then click Enable VB the Autosaves popup does not appear.
Screen cast:
http://youtu.be/RLwRkk1D1xw?hd=1

**Comment by timayhelen** [comment] 2017-02-15 21:43
Looks like this is actually a duplicate ticket, and it has been fixed in the latest version.

**Closed by timayhelen** 2017-02-15 21:43 UTC
Labels: BUILDER SYNC

**Comment by Jronk** [comment] 2017-02-15 22:01
Here are verbose steps to reproduce, and confirmed it is now fixed.

1. Add new page in BB, add columns -> 4_4
2. click "Use Visual Builder"
3. right click admin bar "Edit page", to open in new tab (opens BB in new tab)
4. Add module in VB
5. open page settings bar, click "Publish", wait for complete
6. switch to BB tab
7. sync should happen
8. right click "Use Visual Builder" to open VB in new tab
9. switch to new VB tab
