### ISSUE TITLE
Row editor controls overlap inline editor text (When margin is lowered).

### ISSUE THREAD

**Issue by muffinjello** [elegantthemes/Divi-Beta#93] opened 2016-08-19 05:29 UTC
### Problem:

When inline editing text when the margins on the wrapping row are made smaller, the row controls overlap the text entirely, making editing the text clunky or difficult when this happens. Possibly have it float directly above the row container when the inline-text controls are activated?

![Gif showing issue](https://cdn.pbrd.co/images/aoNa4NABK.gif)

### Steps:
1. Create a page, enter the editor
2. Create a one-column row
3. Add a text module, and some text
4. Lower the top margin on the row, and try editing the first few words.

### Additional Information:

**Browser**: Google Chrome on Windows 10

**Screen Resolution**: QHD Resolution (3200 x 1800)

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment] 2016-09-16 18:32
Looks like a duplicate of this issue - https://github.com/elegantthemes/Divi-Beta/issues/431

**Closed by SlavaET** 2016-09-16 18:32 UTC
Labels: IMPROVEMENT
