### ISSUE TITLE
Boxed Layout :: Snapping settings :: Preview area doesn't adjusting itself when settings is snapped to the edge of the screen

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#475] opened 2016-09-15 16:52 UTC
### Problem:
When a modal settings is being snapped to the left or right side of the screen, the preview area of the layout isn't get adjusted. It remains on the same position which causes part of the preview area located on the bottom of module settings.

### Steps To Reproduce:
1.  Go to Dashboard > Divi > Theme Customizer > General Settings > Layout Settings > Enable Boxed Layout
2. Open any page in VB
3. Try snapping any module settings

### Screenshot or Screencast
here's how the issue looks like:

![boxed layout snapping issue](https://cloud.githubusercontent.com/assets/916442/18558867/f72be838-7b9e-11e6-973b-2ec1abbc2de6.gif)

For comparison, this is what happens if boxed layout is turned off:

![snapping-issue-no-more](https://cloud.githubusercontent.com/assets/916442/18558961/50a86e86-7b9f-11e6-8f06-69861aaddbca.gif)

**Comment by timayhelen** [comment] 2016-09-16 19:29
Looks like the re-sizing the sidebar modal does not trigger responsive breakpoints anymore:

![screen shot 2016-09-16 at 12 28 51 pm](https://cloud.githubusercontent.com/assets/3333028/18598723/37b07c06-7c09-11e6-9e98-b4759667a6fb.png)

**Comment by fikrirasyid** [comment] 2016-09-23 06:26
@timayhelen I've incorporated your feedback at https://github.com/elegantthemes/Divi-Beta/issues/475#issuecomment-247686733

**Comment by timayhelen** [comment] 2016-09-23 19:08
@fikrirasyid Looks good. I found another issue related to modal snap, so I think we can fix it in this PR as well. It's most noticeable with Vertical Nav + Boxed Layout, but it wasn't as apparent before since the content width was not adjusted in boxed mode. 

The issue is, basically, vertical nav gets hidden on mobile but the width of the content area is not adjusted, leaving a blank space to the left of the content where the vertical nav used to be. It results in an incorrect width for the mobile preview and squished content:

![screen shot 2016-09-23 at 12 07 33 pm](https://cloud.githubusercontent.com/assets/3333028/18798244/625ae39c-8186-11e6-95ea-99d6a8e3a4b0.png)

**Comment by fikrirasyid** [comment] 2016-09-24 06:25
@timayhelen I've fixed it at https://github.com/elegantthemes/submodule-builder/commit/9948fc5ed2fb568db16958b2878759f68074fb13

**Comment by lots0logs** [comment] 2016-09-27 01:07
@fikrirasyid I've noticed two issues that are at least somewhat related to what is being addressed in this PR. I marked them in the screenshot below. I also notice another issue where the settings modals are fixed to the top of the browser window and can only be dragged horizontally but since it is currently happening on master branch also, I'll open a new one for it! 

 ![2016-09-26_20-03-35](https://cloud.githubusercontent.com/assets/4675662/18856859/6998cbec-8424-11e6-9d4e-93be95284890.png)

**Comment by fikrirasyid** [comment] 2016-09-27 01:17
@lots0logs ah, I think we can fix the secondary menu issue on this PR. I'll have it done.

**Comment by fikrirasyid** [comment] 2016-09-27 01:21
Regarding modal settings overlaps admin bar, how did you do it? This is how it looks like on my browser:

<img width="1440" alt="screen shot 2016-09-27 at 8 18 10 am" src="https://cloud.githubusercontent.com/assets/916442/18857062/f7423b98-848a-11e6-9a0b-fd4d0233d33f.png">

**Comment by lots0logs** [comment] 2016-09-27 01:29
Hmm..I didnt do anything special. It might not be an issue specific to your changes here. I didnt check for that issue specifically on `master` (but I will check it now..)

**Comment by fikrirasyid** [comment] 2016-09-27 05:01
@lots0logs I can't replicate the admin bar overlapping even if my test site uses transparent background on top and main header.

I've fixed the top header issue at https://github.com/elegantthemes/submodule-builder/pull/1191/commits

**Closed** 2016-09-28 00:05 UTC
Labels: DESIGN SIGNOFF, DEV SIGNOFF, IMPROVEMENT, READY FOR REVIEW
