### ISSUE TITLE
Siteground Timeout Error

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#922] opened 2017-02-07 13:46 UTC
### Problem:

Timeout error pops up even if you add nothing.

### Steps To Reproduce:
1.  Create and Publish new page.
2. Enable Divi Builder and opne VB in a new tab.
3. You should now see the problem.

![1artwork richard slechta - mozilla firefox](https://cloud.githubusercontent.com/assets/3352130/22693575/dd16aad2-ed54-11e6-821d-04c8fcbee530.jpg)

Screen cast
http://youtu.be/slG9XQ-PB2A?hd=1

Test page:
http://elegantthemessiteground.com/wp-admin/post.php?post=198&action=edit

**Comment by timayhelen** [comment] 2017-02-07 18:03
That is normal if the builder fails to load. That failure modal isn't new actually. We need to know the steps to reproduce the error effectively. @kary4

**Comment by timayhelen** [comment] 2017-02-07 18:04
It looks like it might have to do with the way you opened the link. You can see in the URL that the token is undefined.

**Comment by timayhelen** [comment] 2017-02-07 18:52
This is a duplicate of your other issue actually. There is clear steps to reproduce in the other thread.

**Closed by timayhelen** 2017-02-07 18:52 UTC
