### ISSUE TITLE
VB Does Not Save When Various Plugins Are Enabled

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#446] opened 2016-09-12 00:42 UTC
We are seeing this problem a ton, and it seems that various different plugins are to blame. So far I have seen reports of the following plugins causing saving issues:

- Revolution Slider
- Ditty News Ticker

Also, reports of the following modules causing the builder to fail to save:

- Portfolio Module. (https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=590266). I notice that he is using custom hover icons.

Lots of Discussion Here:
- https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=589018
- https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=589155
- https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=589499
- https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=590605
- https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=590498
- https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=590461

Plugins Can Be Downloaded Here:

- [revslider.zip](https://github.com/elegantthemes/Divi-Beta/files/461670/revslider.zip)

**Comment by SlavaET** [comment] 2016-09-12 04:44
Just noticed in one thread:

> Just a note: Yes, I pushed the save button. It changes **_with a x for a moment_** and then return tu the original state, but echa time I close de editor a message pop ups asking if I want to leave the page. Whatever I choose the changes are not saved.

Looks like it's not clear for people that X means error. Probably we should display it in Red or/and display error message if page wasn't saved for some reason. 

P.S. trying to reproduce the issue, no luck so far. Looks like the issue is caused by some specific content, because I have installed all the plugins and FB is saving the page without any errors.

**Comment by SlavaET** [comment] 2016-09-12 04:59
Also, I noticed that about a half of the people who reported that problem simply can't find the real `save` button, looks like they click the Checkmark button in module settings and expect the page to be saved :)
Probably we should always display the `save` button at the bottom right to make it clear for users.

**Comment by timayhelen** [comment] 2016-09-12 05:03
Yeah I will think about it, but there are many many people who can't save and they are clicking the save button correctly.

**Comment by SlavaET** [comment] 2016-09-12 05:06
Yes, I see. Requesting some tokens to look at the specific configurations which cause the issues.

**Comment by timayhelen** [comment] 2016-09-12 05:12
Also from one of the threads: 

> Through process of elimination, I figured it out. The portfolio section on the page is stopping the visual editor from saving the page. Not sure why?
> 
> I went in section by section and deleted each section and the portfolio was the section that finally allowed me to save the page.

**Comment by SlavaET** [comment] 2016-09-12 05:44
I found the at least one configuration of Revolution Slider which breaks the Visual Builder ( imported the slider from one of the customer's website ). Looking for the root cause and solution

**Comment by SlavaET** [comment] 2016-09-12 06:09
Fixed one root cause. VB was not saving if Revolution shortcode was added into the Fullwidth code module.
Looking for other possible root causes.

**Comment by SlavaET** [comment] 2016-09-12 06:45
I'm unable to reproduce the issue with Portfolio module, but I have an idea what may be causing it. Probably it caused by some metadata from computed attributes ( it may contain some unwanted characters which breaks our functions ). So, I added a filter to exclude such attributes before saving. We don't need to save them, therefore no need to process them before saving.

**Comment by SlavaET** [comment] 2016-09-12 18:12
I noticed this weird error on the website where Page with portfolio module is not being saved - http://prnt.sc/ch7gik
Looks like it appears because of big amount of data we're trying to send during the Save, because it includes all the Portfolio metadata. I fixed this issue in my PR.
I tested my fix on his website and it works, the error doesn't appear and page with portfolio module is being saved properly. So, my assumption above seems to be true.

**Comment by SlavaET** [comment] 2016-09-12 18:14
To summarize I fixed 2 main issues in my PR which seem to be the main issues for our customers:
1) Fullwidth Code Module breaks shortcodes
2) Divi trying to send big amount of data if saving the page with Portfolio modules which may also cause the error.

**Closed** 2016-09-12 23:25 UTC
Labels: !IMPORTANT, BUG, DESIGN SIGNOFF, READY FOR REVIEW

**Comment by dm-chechik** [comment] 2016-09-17 16:13
@SlavaET I'm not sure if the following issue in the same scope but the customer still face with problem when pagination option (enable/disable) doesn't work. No matter from wich builder (new VB or old) I switch this option the pagination always displays.
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=588952

**Comment by SlavaET** [comment] 2016-09-17 16:15
It's not related to saving, so it's a different issue, please open a new one with the description of the problem.

**Comment by dm-chechik** [comment] 2016-09-17 16:15
@SlavaET Okay.
