### ISSUE TITLE
Advanced Design - Custom CSS adds <br />

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#673] opened 2016-10-24 16:23 UTC
### Problem:

I can't reproduce the issue locally. I can't find out why on this page http://www.sailorthemes.com/issue-test/  when I add some custom styles to the Custom CSS>Main Element filed (Visual Builder!), then save the changes and click the Edit Page at the very top the custom css looks like:
```
border-color: #cd2122;<br /> color: #fff;<br /> font-size: 22px;
```

Ticket: https://www.elegantthemes.com/forum/viewtopic.php?f=21&t=608135

**Comment by lots0logs** [comment] 2016-10-24 17:34
Duplicate of #666

**Closed by lots0logs** 2016-10-24 17:34 UTC
