### ISSUE TITLE
Touchy Plugin Conflict

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#488] opened 2016-09-17 12:09 UTC
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=593553

**Comment by SlavaET** [comment] 2016-09-19 05:45
Looks like that plugin prevents loading of some basic scripts which are required not only for Visual Builder but for front-end as well, because I see js error on the front-end of the website:
![image](https://cloud.githubusercontent.com/assets/3446682/18623367/01c170a8-7e5e-11e6-9b3b-238be6955dcc.png)

And as far as I can see from his screenshot Underscore.js and Backbone.js along with some others are not loaded correctly ( or not loaded at all ):
![image](https://cloud.githubusercontent.com/assets/3446682/18623405/7750fad2-7e5e-11e6-9d0e-226ffe6c534b.png)


I need to check the plugin to understand whether we can fix it from our side or not. This is the paid plugin, so I'm going to request it from the customer.

**Comment by SlavaET** [comment] 2016-09-21 05:54
I got the plugin from customer and found the root cause. Touchy plugin modified the `exports` global variable and it breaks a lot of things because wp scripts have checks like:
`if (typeof exports !== "undefined") { .... }`
and if `exports` not undefined, then scripts assume it contains required data, but that's not the case, `exports` contains the data added by Touchy plugin and that assumption is wrong, therefore scripts are broken.
Ideally it should be fixed on plugin's side and they shouldn't make such a modification of global variable. 
We can "fix" it from our side though, we can simply dequeue their script which causes the error - it'll partially break the plugin functionality ( specifically Retina Logo feature ), but Visual Builder will work.
I made the PR with solution, but I don't like it because it's definitely an issue on plugin's side, moreover this plugin is not very popular ( about 500 sales ) - https://codecanyon.net/item/touchy-a-wordpress-mobile-menu-plugin/6961708
So, I'm not sure we should add an exception for that single plugin. Probably we can report the issue to developers, to they can fix it in the plugin.
Here is the plugin copy - 
[touchy-by-bonfire.zip](https://github.com/elegantthemes/Divi-Beta/files/484215/touchy-by-bonfire.zip)

@timayhelen what do you think?

**Comment by timayhelen** [comment] 2016-09-21 19:52
@SlavaET Let's not worry about it. Can you update the customer with our findings and then close this issue?

**Comment by SlavaET** [comment] 2016-09-22 04:36
Done.

**Closed by SlavaET** 2016-09-22 04:36 UTC
Labels: ANSWERED, BUG
