### ISSUE TITLE
VB :: Page settings panel completely covers content

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#728] opened 2016-11-07 13:25 UTC
### Problem:

I'm not sure however I expect visible content under the panel is clickable however it's not.
![image](https://cloud.githubusercontent.com/assets/20072036/20059270/67b9f2b2-a506-11e6-9471-c758559902ec.png)
![image](https://cloud.githubusercontent.com/assets/20072036/20059320/bc5525da-a506-11e6-801b-a014dad26474.png)

The marked areas is not clickable.

**Comment by timayhelen** [comment] 2016-11-15 01:41
Interesting, I thought we have pointer events set to none. I wonder if there is a reason we changed it back?

**Comment by fikrirasyid** [comment] 2016-11-19 09:44
@timayhelen @dm-checknik related to the first image, page bar is actually 100% width rectangle on the bottom of the page with transparent background, so everything beneath it is basically unhoverable. If I recall correctly, we intentionally keep it that way to avoid any actions which is triggered by hover to perform when the cursor moves from centered button groups to left/right aligned button groups.

![67b9f2b2-a506-11e6-9471-c758559902ec_png__1323x582_](https://cloud.githubusercontent.com/assets/916442/20454579/6092e15e-ae77-11e6-9959-4cd9a874832c.jpg)


Regarding the second image, I don't recall we have a specific fix for it. Media library modal is basically hovered on top of the page with fixed margin relative to the window. We might probably need to adjust the media library's `bottom` / `margin-bottom` value when page bar is expanded. I'll work on it.

**Comment by fikrirasyid** [comment] 2016-11-19 10:28
Note: I updated my previous reply.

**Comment by SlavaET** [comment] 2016-11-21 05:43
I can confirm that we fixed the issue with Media Uploader button covered by Page Settings Bar.

**Comment by lots0logs** [comment] 2016-11-21 19:37
@fikrirasyid Let's just ensure that the tooltips and modals are always positioned where they do not overlap the page settings bar (when the viewport is tall enough of course).

**Comment by fikrirasyid** [comment] 2016-11-22 11:48
@lots0logs I've pushed https://github.com/elegantthemes/submodule-builder/pull/1460 which achieved what you mentioned by `ensure that the tooltips and modals are always positioned where they do not overlap the page settings bar`. However it is kinda contradicting with @timayhelen's decision of not limiting modal dimension to window at https://github.com/elegantthemes/Divi-Beta/issues/605#issuecomment-253173019. I can see the reason of doing so on this PR which is to avoid confusion of unclickable DOM below page settings bar tho.

ATM, this is how the PR works:

Prevent modal to be placed below page settings bar. When page settings bar is closed, everything works as usual:

![728-normal](https://cloud.githubusercontent.com/assets/916442/20521330/52d227c4-b0dd-11e6-923f-7cd252aee0d6.gif)
*Moving / Dragging*

![728-resize-normal](https://cloud.githubusercontent.com/assets/916442/20521363/80b7ab64-b0dd-11e6-85b8-a9f6f6ec4691.gif)
*Resizing*

However when page settings bar is opened, modal's height and position will be automatically corrected so it can never be placed below page settings bar which will avoid confusion due to unclickable state (everything below page settings bar is actually overlay-ed by page settings bar itself so no action can occur):

![728-fixed](https://cloud.githubusercontent.com/assets/916442/20521375/914e63d2-b0dd-11e6-8ebe-c7ce5d1469fb.gif)
*Moving / Dragging*

![728-resize-pr](https://cloud.githubusercontent.com/assets/916442/20521398/a8fff50e-b0dd-11e6-8177-9d7cd9faef3b.gif)
*Dragging*

**Comment by lots0logs** [comment] 2016-11-22 14:26
@fikrirasyid Hmm..actually what I meant was that we should make sure that we don't position the modals/tooltips beneath the settings bar whenever they are opened. Beyond that the user should be able to drag them wherever they want. Sorry I wasn't very clear in my last comment :grimacing:

**Comment by fikrirasyid** [comment] 2016-11-23 00:16
@lots0logs can you elaborate more on what you mean by `we don't position the modals/tooltips beneath the settings bar whenever they are opened`? Isn't it what the following does? 

![728-fixed](https://cloud.githubusercontent.com/assets/916442/20521375/914e63d2-b0dd-11e6-8ebe-c7ce5d1469fb.gif)
*Moving / Dragging*

![728-resize-pr](https://cloud.githubusercontent.com/assets/916442/20521398/a8fff50e-b0dd-11e6-8177-9d7cd9faef3b.gif)
*Dragging*

**Comment by lots0logs** [comment] 2016-11-23 02:37
@fikrirasyid I mean that when a modal/tooltip is made visible it should be positioned above the settings bar. Beyond that, the current behavior should stay in place (which is that the modals can be dragged anywhere without restriction. So for example, if the user was to drag the modal to a position that puts it behind the settings bar and then saves/closes it. The next time it is opened it should be positioned above the settings bar (so basically its X coordinates would remain the same but its Y coordinates would be adjusted if necessary to ensure it isnt behind the settings bar) Does that make sense?

**Comment by fikrirasyid** [comment] 2016-11-23 10:02
@lots0logs Ah I see. So what you mean is do the prevention mechanism (what the PR has done) **only when the modal is being opened**?

We can do it and it certainly will not contradicting with @timayhelen's decision at https://github.com/elegantthemes/Divi-Beta/issues/605#issuecomment-253173019, but isn't it only half-fixed the issue? It surely fixes the issue **IF** user doesn't move the modal. However, If s/he moves the modal, what @dm-chechik reported on this issue will appear again.

What do you think?

**Comment by lots0logs** [comment] 2016-11-24 00:13
@fikrirasyid I think that if the user move's the modal where its blocked by the settings bar then they can just as easily move it back into a better position. I don't think its necessary for us to force anything on the user (which is inline with the decision made at https://github.com/elegantthemes/Divi-Beta/issues/605#issuecomment-253173019)

**Comment by fikrirasyid** [comment] 2016-11-24 09:13
@lots0logs I'm closing the previous PR and opened new one which incorporating your feedback at https://github.com/elegantthemes/submodule-builder/pull/1472

This is the PR message which explains how the PR works:

> Fixes https://github.com/elegantthemes/Divi-Beta/issues/728
> 
> Specifically, incorporating @lots0logs feedback at https://github.com/elegantthemes/Divi-Beta/issues/728#issuecomment-262254015
> 
> FB actually already has `modal position correction when the modal is opened` if part of modal is positioned outside the viewport. This commit/PR improves the mechanism by moving the modal position when the modal is being opened if the last saved modal position is positioned beneath page settings bar and page settings bar is currently opened.
> 
> Thus, assume modal is closed while positioned beneath page settings bar:
> 
> 1. If page settings bar is expanded when the modal is opened, the modal will be automatically moved upward (bottom = 150px relative to window)
> 2. If page settings bar is closed when the modal is opened, the modal will remain opened on its position.
> 
> ![728-remains](https://cloud.githubusercontent.com/assets/916442/20592205/cebc9af4-b25e-11e6-8275-1d77ba787b3d.gif)
> *Page settings bar is closed == modal position remains*
> 
> ![728-moved](https://cloud.githubusercontent.com/assets/916442/20592236/ec0f3e86-b25e-11e6-8027-1586dfc890b2.gif)
> 
> *Page settings bar is opened == modal position is moved*
> 
> ***
> 
> ## Note
> The tricky part about this PR is we need to determine the height of modal header and footer on `constructor` (modal/index actually calculates the height of modal footer and header on `componentDidMount`, but it is too late for this implementation) when the DOM hasn't been painted yet (thus makes it impossible to calculate the actual printed DOM on the page). To fix it, we're setting a hardcoded best-guessed fixed value which is used by getting position x & y (which will be overwritten by actual value on `componentDidMount`)

**Closed** 2016-11-30 01:05 UTC
Labels: DESIGN SIGNOFF, IMPROVEMENT, QUALITY ASSURED, READY FOR REVIEW
