### ISSUE TITLE
VB :: Modifying padding via padding UI breaks circle counter JS initialization

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#976] opened 2017-02-13 10:41 UTC
### Problem:

For example Circle Counter Module does not update value anymore if you change Column Structure under VB.

### Steps To Reproduce:
1.  Add Circle Counter and define any value, close the settings popup window.
2. Change Column Structure and you'll see the problem.

Screen cast:
http://youtu.be/TU9dEBQz1lQ?hd=1

## Attached PR

- https://github.com/elegantthemes/submodule-builder/pull/1719

**Comment by timayhelen** [comment] 2017-02-14 00:19
This probably applies to a lot of things. Testimonial re-size, slider re-size, background video ajax call, etc.

**Comment by fikrirasyid** [comment] 2017-02-14 04:11
@kary4 I've followed the reproducing steps you're given (even following the video step by step, see: https://www.dropbox.com/s/r4qlpmbn7gvlvxt/divi-beta-976-issue.mov?dl=0) but I still couldn't reproduce the issue. Can you do the following?

1. Clear your browser cache
2. Open devtool > console
3. Reproduce the steps you've mentioned
4. If the issue remains, can you screenshot the console log output?

**Comment by kary4** [comment] 2017-02-14 10:46
@fikrirasyid That's strange, it was so easy to replicate this problem earlier, but now I cannot replicate it as well the way I described above. So, I spent a lot of time to understand how this can be replicated. Finally I was able to reproduce the problem, but I'm afraid I cannot describe the exact steps. The good news is that I took a screen cast so you can see all the error messages:
http://youtu.be/MrEXDBAF5rI?hd=1

Let me know what you think.

**Comment by fikrirasyid** [comment] 2017-02-14 15:41
@kary4 thanks for the screencast, I can replicate it now. Basically circle counter js init is stopped when padding is modified via padding UI. I'm investigating it now

**Comment by fikrirasyid** [comment] 2017-02-14 16:10
I've checked this issue based on the last feedback from @kary4 (see: https://github.com/elegantthemes/Divi-Beta/issues/976#issuecomment-279673602) and it appears that this issue appears on `master` as well. Thus:

1. This isn't builder specific issue
2. The PR is merged to `master`.

**Comment by kary4** [comment] 2017-02-14 21:41
Okay, I can test this when Divi Builder will be updated on the test servers.

**Closed** 2017-02-15 01:36 UTC
Labels: BUG, DESIGN SIGNOFF, QUALITY ASSURED, READY FOR REVIEW
