### ISSUE TITLE
Video Slider :: Display Image Overlays on Main Video doesn't work

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#339] opened 2016-09-05 13:39 UTC
### Problem:

Display Image Overlays on Main Video option doesn't work.

### Steps To Reproduce:
1. Upload .mp4/.webm video 
2. Upload Image Overlay
3. Change Display Image Overlays on Main Video
4. 

![video slider](https://cloud.githubusercontent.com/assets/9657712/18249471/4dda8812-73a0-11e6-81c7-5a2bda6050d9.gif)

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**: w7

**Browser**: chrome

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment] 2016-09-15 06:36
@andrey-agp I cannot reproduce this issue in the latest version and it works correctly. Can you please check whether or not it still happening to you?

**Comment by andrey-agp** [comment] 2016-09-15 06:39
@SlavaET I cannot reproduce this issue in the latest version and it works correctly.

**Comment by SlavaET** [comment] 2016-09-15 06:40
great, closing it then.

**Closed by SlavaET** 2016-09-15 06:40 UTC
Labels: BUG, QUESTION
