### ISSUE TITLE
Visual Builder Doesn't Retain Modules' Custom CSS Classes

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#425] opened 2016-09-09 12:46 UTC
### Problem:

It seems new visual builder doesn't grubb or apply custom css with media queries. 

### Steps To Reproduce:
1. Create custom css for mobile layout in the ePanel (for example @media only screen and (max-width: 479px) )
2. Switch to Visual Builder
3. Change layout to mobile
4. Custom css doens't applied

**Comment by lots0logs** [comment] 2016-09-12 15:49
I've also noticed that custom CSS classes assigned to a module are not picked up by the VB. It simply shows that there are none. If you dont notice it and you save the page then it will save the module without any custom class.

**Comment by SlavaET** [comment] 2016-09-12 18:27
@dm-chechik our responsive preview doesn't emulate real responsive preview. It only works with Divi default modules and settings, it won't work with the custom css for media queries.

**Comment by dm-chechik** [comment] 2016-09-12 21:01
@SlavaET I think the customers don't want to hear it :) Is there any documentation about it?

**Comment by lots0logs** [comment] 2016-09-12 21:37
@dm-chechik You can simply explain to them that the Visual Builder must have control over the elements styles in order to work properly. Only styles that they input directly in the module settings will be reflected while the Visual Builder is active. External styles will of course still be shown on the page when its not viewed inside the Visual Builder.

**Comment by SlavaET** [comment] 2016-09-13 06:35
@lots0logs I cannot reproduce the issue you're talking about. I can see all the classes correctly and they do not disappear after saving. Do you see this issue in specific modules?

**Comment by lots0logs** [comment] 2016-09-13 07:53
@SlavaET I'm dont remember exactly, I think it was a blurb module :grimacing:

**Comment by SlavaET** [comment] 2016-09-13 08:16
@lots0logs can you still reproduce the issue? It works fine for me. It appears in the field with a small delay sometimes, but it's still there and it doesn't allow to accidentally erase the classes.

![saving-classes](https://cloud.githubusercontent.com/assets/3446682/18466178/77af5218-79bc-11e6-86af-9aa9801e8712.gif)

**Closed** 2016-09-13 18:58 UTC
Labels: !IMPORTANT, BUG, QUESTION
