### ISSUE TITLE
Dreamhost :: Builder Sync :: Adding row

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#938] opened 2017-02-08 11:06 UTC
### Problem:

Adding row from Library in BB generate Js error, while repeating the same process in VB works, and it also updates the BB.

https://drive.google.com/open?id=0B8PjD3Z_XQvueXA1TWo2UXdCZnc

**Comment by fikrirasyid** [comment] 2017-02-16 04:48
This is duplicate of https://github.com/elegantthemes/Divi-Beta/issues/955 which has been fixed on latest `575-fix-heartbeat-content-smashing-wip`

**Closed by fikrirasyid** 2017-02-16 04:48 UTC
Labels: BUILDER SYNC
