### ISSUE TITLE
Draggable Section Padding Overwritten By Theme Customizer CSS In Visual Builder Responsive Preview

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#897] opened 2017-01-12 00:56 UTC
1. Using **Theme Customizer > Mobile Styles > Phone > Section Height** setting, add a custom value to the section height field. 
2. Open a page in the Visual Builder and toggle the Smartphone Responsive Preview mode. 
3. Attempt to drag the padding of a section. The visual indicator will drag, but padding will not be adjusted. This is because the Theme Customizer settings is overwriting the module setting. 

The reason that the Theme Customizer settings are overwriting the Visual Builder CSS is because of the way that Theme Customizer CSS is altered in the Visual Builder so that it can be applied to our pseudo Responsive Previews without using normal browser breakpoints. The CSS becomes much more specific:

```
.et_fb_preview_active.et_fb_preview_active--responsive_preview.et_fb_preview_active--responsive_preview--phone_preview .et_pb_section {
    padding: 100px 0;
}
```

Which overrides:

```
.et_pb_section_2.et_pb_section {
    padding-top: 303px;
    padding-right: 0px;
    padding-bottom: 211px;
    padding-left: 0px;
}
```

It works fine for rows because we, for some reason, using !important on all row padding values when customized in the builder.

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1570

**Comment by lots0logs** [comment] 2017-01-16 19:04
@fikrirasyid Dragging the padding value still doesn't work correctly:

![2017-01-16 13-03](https://cloud.githubusercontent.com/assets/4675662/21995777/56496a04-dbec-11e6-892f-d3bb005b1968.gif)

**Comment by timayhelen** [comment] 2017-01-16 19:19
@lots0logs That's probably this bug, you might want to check the CSS:

https://github.com/elegantthemes/Divi-Beta/issues/905

**Comment by fikrirasyid** [comment] 2017-01-16 23:42
@lots0logs can you send me the layout you're using?

**Comment by fikrirasyid** [comment] 2017-01-17 01:04
@lots0logs have you tried clearing your browser's cache first? I tried re-checking this issue and it initially works as you mentioned. However after I cleared my browser's cache, it works as expected:

![897-works-as-expected](https://cloud.githubusercontent.com/assets/916442/22004101/89eeca12-dc8b-11e6-97f3-3fde1f0005d7.gif)

If you're still seeing the issue after you clear your browser's cache, can you send me both the exported file of your builder and your customizer? Thanks.

**Comment by lots0logs** [comment] 2017-01-17 01:07
@fikrirasyid Yeah I tried clearing the cache a few times. It's not working. Well, its not working completely I should say. The builder correctly saves the custom padding value after dragging but it doesnt apply it with CSS so visually it appears not to be working. You can check it out right now on the homepage of my test site.

**Comment by fikrirasyid** [comment] 2017-01-17 01:15
@lots0logs I've checked your site and @timayhelen is correct. The section you're testing is experiencing the bug that is being fixed at https://github.com/elegantthemes/Divi-Beta/issues/905.

Try the following:

1. Open the section's setting modal
2. Toggle on its padding responsive mode
3. Close the modal, try dragging the padding again.

Or, since the issue is basically customizer related, create new page and see whether the issue mentioned on this ticket remains or not (I've tested it and it is fixed by this branch you used on your test site)

**Comment by timayhelen** [comment] 2017-01-17 01:26
@fikrirasyid @lots0logs Yeah it was the other bug. 

However, we found a new issue with this PR. It looks like it fixes the problem for top and bottom padding for sections, but not for left and right padding. 

1. Adjust the Tablet and Phone sections height in the Theme Customizer. 
2. Enabled the Tablet or Phone responsive preview mode in the Visual Builder. 
3. Drag the left and right padding. 

The issue is that the pseudo responsive CSS is still overwriting the left and right paddings:

![screen shot 2017-01-16 at 5 12 30 pm](https://cloud.githubusercontent.com/assets/3333028/22004500/d1fef9ec-dc10-11e6-8fb2-f38480530a82.png)

![screen shot 2017-01-16 at 5 21 43 pm](https://cloud.githubusercontent.com/assets/3333028/22004505/da9979a6-dc10-11e6-89c9-7ea47910f2af.png)

**Comment by fikrirasyid** [comment] 2017-01-17 02:55
@timayhelen thank you for noticing that. I intentionally limited the fix on padding-top and bottom because customizer's section height appeared to only modify its vertical value only. However, it turned out that customizer's output modifies padding left & right to `0` thus makes 535c11ff3b9c33dc6dd5738344414da6917fe49c needs to be applied on padding left and right as well.

I've pushed a commit which should've fixed the issue 👍

**Closed** 2017-01-18 00:53 UTC
Labels: BUG, DESIGN SIGNOFF, QUALITY ASSURED, READY FOR REVIEW
