### ISSUE TITLE
Error message :: Warning: A non-numeric value encountered

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#836] opened 2016-12-12 01:32 UTC
### Problem:
I can't find out where the error message comes from. I tried even installing a fresh divi veersion. It's the same problem. It's php 7.1. version. Can someone take a look please?

http://iajco.org/
Ask me for a token.

![page not found - chichester vedic society - mozilla firefox](https://cloud.githubusercontent.com/assets/3352130/21085501/f7a3976a-c023-11e6-85a0-2881002375b0.jpg)

Ticket:
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=627339

**Comment by SlavaET** [comment] 2016-12-12 05:37
I was not able to reproduce the error, but I found an error in the function which calculates the Widgets Header font-size on line `5852`.
I corrected that error in my PR, so it should fix the issue.

**Comment by timayhelen** [comment] 2016-12-13 01:16
@SlavaET It looks like your fix changes the logic of the option. 

` et_get_option( 'widget_header_font_size', intval( et_get_option( 'body_header_size', '18' ) ) * .6 )`

It was originally written like this to mean:

1. Check to see if **widget_header_font_size** option has been modified.
2. If not, use the default vale. 
3. The default value is pulled from the **body_header_size** if it has been modified, and then multiplied by .6. 
4. If neither the **widget_header_font_size** or **body_header_size** options have been modified, we use the final default value of 18. 

You change seems to multiple the default value of 18 by .6, but that shouldn't happen. Also, this error exists in two places so we need to fix it in both (keep the logic but fix the syntax error).

**Comment by kary4** [comment] 2016-12-13 02:05
By the way, that fix works. Thanks @SlavaET !

**Comment by SlavaET** [comment] 2016-12-13 05:14
@timayhelen fixed in both places.
I simplified the logic slightly:
1) Check to see if widget_header_font_size option has been modified.
2) If not, use the default vale.
3) The default value is pulled from the body_header_size and multiplied by .6.

On step 3 we'll receive either default `body_header_size` which is `30` or modified `body_header_size` value. So, if `body_header_size` was not modified, then we'll receive 30 and `30 * 0.6 = 18`. The exact number we need if nothing was modified.

**Closed** 2016-12-15 23:32 UTC
Labels: BUG, DESIGN SIGNOFF, QUALITY ASSURED, READY FOR REVIEW
