### ISSUE TITLE
Bar Modules :: Use Percentages options doesn't update in real time

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#279] opened 2016-09-01 15:00 UTC
### Problem:

Enabling / disabling the Use Percentages option, doesn't update the Bar Modules in real time, you will have to edit each of the items to see the option in action.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: desktop

**Operating System**: mac os x

**Browser**: Chrome

**Screen Resolution**:

**Screenshot or Screencast**:
https://drive.google.com/file/d/0B8PjD3Z_XQvuWlc0VU4yOGo3Vlk/view?usp=sharing

**Comment by SlavaET** [comment] 2016-09-01 15:11
Duplicate of https://github.com/elegantthemes/Divi-Beta/issues/249

**Closed by SlavaET** 2016-09-01 15:11 UTC
