### ISSUE TITLE
Visual Builder :: Modules Disappearing 

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#884] opened 2017-01-09 22:08 UTC
### Problem:

The issue comes from this ticket -> https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=630687
It seems the issue due to broken page layout because on front end I see raw shortcodes
![image](https://cloud.githubusercontent.com/assets/20072036/21785484/cc758bc0-d6d0-11e6-8b6f-67d821d1568c.png)
 
Also the Backend Editor crashes with the following error
![image](https://cloud.githubusercontent.com/assets/20072036/21785539/033c6ed0-d6d1-11e6-9c9a-c542a0aea7aa.png)

**Link To Download Layout JSON File**:
https://www.dropbox.com/s/n5xveagupdjiww0/sheds.json?dl=0

**Comment by SlavaET** [comment] 2017-01-18 11:01
Yes, this error appears because of broken layout of Specialty Section. I think it became broken after user inserted the Row from Library into Specialty Section using the Visual Builder. I fixed that bug and should not happen any longer after the fix will be included into Divi theme. 
But my fix won't correct the broken layout, so the customer should build the new page to fix this error.
Also, you can tell the customer not to add the Rows into specialty sections from library using the VB until the fix will be released.

Steps to Reproduce: 
1) Open page in the VB;
2) Add Specialty Section on page;
3) Add Row into the section from the Library;
4) Save the page;
5) Open the page for editing in BB;
6) Notice the error. Also, if you refresh the page in VB, you'll see the broken layout as well.

@timayhelen @lots0logs is it a widespread issue and do we need to include a patch which will correct the existing broken layouts?

**Comment by timayhelen** [comment] 2017-01-18 21:21
@SlavaET This creates a new issue. Now if you do the reverse (save a row from a specialty section to the library and then add that row to a normal section) the layout is broken.

![screen shot 2017-01-18 at 1 21 24 pm](https://cloud.githubusercontent.com/assets/3333028/22083455/07b715bc-dd81-11e6-9d86-66e566dd4f30.png)

**Comment by timayhelen** [comment] 2017-01-18 21:27
@SlavaET Actually now I can't see to reproduce it with the steps mentioned above. Still looking into it.

**Comment by timayhelen** [comment] 2017-01-18 21:31
@SlavaET It seems to only occur if you don't save the page during the process.

1. Start with a blank page. 
2. Add a normal section and a specialty section.
3. Save a normal row to the library. 
4. Save a specialty row to the library. 
5. Add the normal row inside the specialty section.
6. Add the specialty row inside the normal section. 
7. Save the page.

**Comment by timayhelen** [comment] 2017-01-18 21:38
@SlavaET Here is the layout created in the above screenshot:

https://www.dropbox.com/s/e2xi0oes8yu7zbl/Specialty.json?dl=0

**Comment by timayhelen** [comment] 2017-01-19 01:04
@fikrirasyid was able to fix the issue before we released a new version last night.

**Closed** 2017-01-19 01:03 UTC
Labels: !IMPORTANT, BUG, DESIGN SIGNOFF, QUALITY ASSURED, READY FOR REVIEW
