### ISSUE TITLE
Slider Module :: Incorrect slider height calculation

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#844] opened 2016-12-14 16:35 UTC
### Problem:

The issue comes from this ticket -> https://www.elegantthemes.com/forum/viewtopic.php?f=21&t=625937.
It seems the issue occurs when slider does not have any content.
As a result slider height calculates incorrectly under different browsers.

**Comment by SlavaET** [comment] 2016-12-15 06:15
@dm-chechik I checked the customer's website in all 3 browsers and I can see the slider in all of them. The only issue I see is the different width of slider in FireFox browser. 
I cannot reproduce this issue locally though, probably there are some specific settings which affect the appearance. Can you please export the layout of that page from the website in question and share it with me?

**Comment by dm-chechik** [comment] 2016-12-16 18:11
@SlavaET Sorry for delay. Here the page layout -> https://www.dropbox.com/s/kdj47l5bihcpzx0/layout-for-issue-884.zip?dl=0

**Comment by SlavaET** [comment] 2016-12-19 10:51
Fixed the issue when empty slides were displayed with wrong height in FireFox.
@dm-chechik can you reproduce the issue described in original customer's ticket? I fixed a different issue, because it's the only issue I see.

**Comment by dm-chechik** [comment] 2016-12-20 15:46
@SlavaET I've imported the layout to my test enviro. 
This is how it looks under FireFox browser.
![image](https://cloud.githubusercontent.com/assets/20072036/21356981/a00875d0-c6e4-11e6-89dd-bed3141d4431.png)

**Comment by SlavaET** [comment] 2016-12-20 16:28
Yes, this is the issue I fixed in my PR, but can you reproduce the issue described by customer?

**Comment by dm-chechik** [comment] 2016-12-20 16:31
@SlavaET Did you mean this?
> Safari= Shows OK but cuts a little off the top of the picture
> Firefox=Shows the Best with the biggest picture
> Chrome=No slider at all
I can't reproduce this

**Comment by SlavaET** [comment] 2016-12-20 17:22
Yeah, I meant that. I can't reproduce it either.

**Closed** 2016-12-23 00:50 UTC
Labels: BUG, DESIGN SIGNOFF, QUALITY ASSURED, READY FOR REVIEW
