### ISSUE TITLE
Broken slider input on advanced setting button fields

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#663] opened 2016-10-22 00:52 UTC
### Problem:
When slider input on advanced settings tab on button module's setting is changed, it opens other slider input's responsive mode.

Note: most slider input doesn't cause this issue. I found this on button modules' advanced options button input slider.

### Steps To Reproduce:
1. Add button module 
2. Open button module's settings
3. Switch to advanced design tab
4. Enable `Use Custom Styles For Button`
5. Scroll to bottom of settings screen, and try to modify `Button Hover Letter Spacing` value by dragging the slider
6. You'll see irregularity: the screen jumps, and the responsive mode of the slider input above  `Button Hover Letter Spacing` being modified.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:
Macbook Pro Retina 15"

**Operating System**:
OSX El Capitan

**Browser**:
Latest Chrome

**Screen Resolution**:
2560x1440 + 1440 x 900 (dual monitor)

**Screenshot or Screencast**:
![le-slider-input-issue](https://cloud.githubusercontent.com/assets/916442/19615626/44071dae-982c-11e6-8585-8f24dd32028c.gif)

**Link To Download Layout JSON File**:
[Le Button Issue.json.zip](https://github.com/elegantthemes/Divi-Beta/files/545492/Le.Button.Issue.json.zip)

**Comment by fikrirasyid** [comment] 2016-10-22 10:25
@SlavaET since this commit related to https://github.com/elegantthemes/Divi-Beta/issues/652 which you were working on, is it possible for you to take a look at this issue's PR just in case I'm missing something? Thanks :D

**Comment by SlavaET** [comment] 2016-10-24 05:55
@fikrirasyid your fix doesn't seem to affect the functionality added here - https://github.com/elegantthemes/Divi-Beta/issues/652
Everything work as expected.

**Comment by lots0logs** [comment] 2016-10-24 18:50
@fikrirasyid 

![2016-10-24 13-44](https://cloud.githubusercontent.com/assets/4675662/19659181/a09ea17a-99f0-11e6-9cda-19b19268199a.gif)

The same error from #664 shows in console though I was not doing DnD (as you can see)

**Comment by timayhelen** [comment] 2016-10-24 18:59
@SlavaET @fikrirasyid I noticed something else while looking into this issue, related to https://github.com/elegantthemes/Divi-Beta/issues/652

I didn't realize that this PR automatically enabled responsive editing for all settings while responsive previews are enabled. This shouldn't be the case. Basically we should hide the responsive editing tabs unless they have been enabled. If they have not been enabled, then the setting can be adjusted normally (and it will affect all breakpoints).

For settings in which responsive editing has already been enabled, then we keep the active tab in sync with the current responsive preview mode. But for all settings in which responsive editing has not been enabled we don't need to do anything.

**Comment by lots0logs** [comment] 2016-10-24 19:42
@timayhelen Can't believe we missed that! :doh: ..Though if I remember correctly, part of the original issue was being kicked out of responsive preview mode just because you attempted to edit a setting without first switching to the responsive controls for that setting. I'm not sure how we address that without enabling the responsive controls when the preview mode is active? If you are in tablet mode you probably dont want to affect all responsive views when you change a setting. Its a hassle to have to first switch to the responsive controls when you are already in responsive preview mode. 9 times out of 10 I personally, forget to switch before making a change and it kicks you out of the preview mode and back to desktop mode. How can we address that?

**Comment by timayhelen** [comment] 2016-10-24 19:49
@lots0logs It's fine that the adjustments affect all breakpoints until responsive editing is enabled. It should be a choice not a requirement in my opinion, and that's how it was intended to work. 

`9 times out of 10 I personally, forget to switch before making a change and it kicks you out of the preview mode and back to desktop mode. How can we address that?`

It wont't kick you to desktop because you aren't editing the "desktop" responsive zone, you are just editing the setting normally just like all other settings. It's not that case that every time you edit a setting while responsive previews are enabled that it kicks you to desktop. If responsive editing _is_ enabled it is synced to your current responsive preview.

**Comment by lots0logs** [comment] 2016-10-24 21:00
>It wont't kick you to desktop because you aren't editing the "desktop" responsive zone, you are just editing the setting normally just like all other settings. 

That was not the behavior when I created #594 ..is that not related to what we're talking about here? Perhaps I misunderstood :grimacing:

**Comment by timayhelen** [comment] 2016-10-24 21:02
@lots0logs When responsive editing is enabled, the active tab is synced with the current responsive preview. That's what was fixed in Slava's PR. When responsive editing is not enabled, there was never an issue when being kicked out of the current responsive preview.

**Comment by timayhelen** [comment] 2016-10-24 21:10
Never mind I guess there was an issue, but there shouldn't be. So this is how it should work:

1. When responsive editing is _not_ enabled, never change the responsive preview mode while editing. There is no reason to because, without responsive editing enabled, the adjustments will affect all breakpoints. 
2. When a responsive preview toggled, all options with responsive editing _enable_ should have their active tab changed to match the current responsive preview mode. Likewise, if a responsive preview tab is changed, it should change the responsive preview mode. 
3. Toggling responsive preview modes should have no affect on modules that do not have responsive editing enabled. 

So we need to fix three things:

1. Fix the bug that this issue was opened for. 
2. Prevent responsive previews from being toggled when editing settings that do not have responsive editing enabled. 
3. Do not automatically enabled responsive editing when toggled responsive previews.

**Comment by lots0logs** [comment] 2016-10-24 21:12
@timayhelen I was really scratching my head at your previous comment :confused:  I thought I might be losing my mind or something lol

**Comment by lots0logs** [comment] 2016-10-24 21:16
So lets say I have responsive preview mode set to mobile phone view and I open the advanced design settings tab where I've never editing any settings before (so no responsive settings are enabled). When I edit one of the settings without first enabling responsive mode that will affect all views? Even though I am in the mobile phone view? I don't think that is desireable nor expected behavior :grimacing:

**Comment by timayhelen** [comment] 2016-10-24 21:17
@lots0logs Yes that is how it should work.

**Comment by lots0logs** [comment] 2016-10-24 21:18
If I am looking at the mobile view I think its safe to say when I edit a style I want to edit it for mobile. I wouldnt expect to be editing the style for all views. Am I crazy?

**Comment by timayhelen** [comment] 2016-10-24 21:25
@lots0logs It's not how I want it to work and it's doesn't make sense to me due to how the feature is currently implemented.

**Comment by lots0logs** [comment] 2016-10-24 21:29
@timayhelen  

![okay](https://cloud.githubusercontent.com/assets/4675662/19664644/037cde68-9a07-11e6-8b75-3e9c9b00828b.gif)

**Comment by fikrirasyid** [comment] 2016-10-25 02:26
@lots0logs @timayhelen @SlavaET I've pushed commit which should fix the issue mentioned by @timayhelen at https://github.com/elegantthemes/Divi-Beta/issues/663#issuecomment-255867163.

Notes: it turns out that input text responsive component (like the one that is used by Blurb's advanced tab image max width) has the same unwanted behaviour so I implemented the patch on responsive input as well.

**Comment by fikrirasyid** [comment] 2016-10-25 15:51
@timayhelen I've pushed several commits to this PR. It turns out the last newly found bug you mentioned via Slack brought me to found out lots of bugs which actually existing at `master`. I end up checked everything that can be check related to the responsive input and fixed them. These are things to know about responsive inputs:

***

1. There are three responsive inputs: text, range, and margin/padding input. 
2. Previously, VB's responsive input mimic exactly how BB's responsive input works: each field has five values: desktop, tablet, phone, isResponsive, and last edited field.
3. Later on, the way VB's responsive input is tweaked to utilize VB's strength. Responsive input is synced to VB's responsive preview mode. However, the "currently implemented responsive input matches page's responsive mode" has one major flaw: it ignores the field's `isResponsive`. Thus `isResponsive` is automatically turned on if the page's responsive mode is switched. This is incorrect behaviour because responsive input works in cascading way: it has specific breakpoint styling, but if `isResponsive` value is set to `false`, the non-responsive value is used for all breakpoints.
4. Considering no. 3, this PR fixes the flaw it currently has by basically: only matches the responsive field's last edited value if user explicitly activating the field's `isResponsive` value by clicking the phone icon.

This seems to be straight to the point while actually moving from no. 3 to no. 4 (responsive being synced to all field vs only synced explicitly activated field) breaks lots of syncing relationship added when responsive field was moving from no. 2 to no. 3 (exactly like BB vs all field synced to page's responsive view). Furthermore, while we're doing 2 to 4, we change the way VB's shortcode object work. Previously, VB's shortcode object is printed on the page directly. Due to the performance reason, now fetch the shortcode object via AJAX.

Consequently:

1. The shortcode object change causes lots of conditionally passed attributes for passing isResponsive and last edited data didn't get passed. What this causes are: if you change responsive inputs at section, row, row inner, button, text, image, CTA, search, and fullwidth code modules, save the page, refresh the page, then opening the module's settings, the module won't automatically expand the edited responsive inputs. This happened because the attributes didn't get sent from the backend.
2. Active tab state becomes really erratic, especially when preview mode is changed via page's setting bar (the bottom left buttons)
3. Some range input doesn't get changed even if the scroll bar is being dragged. This was caused by the unmatch active tab and active inputs.

## Note
There is one notable differences on how active tab works on VB. BB saves these two things:

- isResponsive
- lastEdited mode

In BB, assume the last edited is phone, the next time settings are opened, the settings that are opened by default are phone. However, this last edited field is ignored in VB. The tab that is opened is always matched with current page's responsive mode as it is more intuitive.

**Comment by lots0logs** [comment] 2016-10-25 17:08
![2016-10-25_12-06-03-pm](https://cloud.githubusercontent.com/assets/4675662/19696170/af07116e-9aab-11e6-9bcd-6679b31ba5f1.png)

**Comment by lots0logs** [comment] 2016-10-25 17:18
I tested this branch thoroughly both the BB and VB and didnt find any issues (that arent already on master anyway :stuck_out_tongue_winking_eye: ) :+1:

**Closed** 2016-10-25 19:25 UTC
Labels: BUG, CI :: TEST CANDIDATE, DESIGN SIGNOFF, QUALITY ASSURED, READY FOR REVIEW
