### ISSUE TITLE
Row Background Color Doesn't Save For Globa Rows

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#623] opened 2016-10-11 20:46 UTC
Whenever you save a row to the library as a global row, the Background Color changes to a light blue color and you can't update it.

**Comment by fikrirasyid** [comment] 2016-10-13 09:46
Is there any specific steps that need to be done? I've tried various ways to replicate the issue, but it works as expected:

1. Configure row
2. Save as global item
3. Publish the page 
4. Check on front page: works as expected
5. Modify global row's background
6. Update the page
7

**Comment by fikrirasyid** [comment] 2016-10-13 10:17
@timayhelen In case the issue about global module not being saved while it is being opened in modal setting is correct, I've submitted https://github.com/elegantthemes/submodule-builder/pull/1309 to fix it.

**Comment by lots0logs** [comment] 2016-10-13 19:24
@fikrirasyid Please see my comment on the PR. Thanks :smiley: 

@timayhelen Could you confirm that the issue is indeed what @fikrirasyid described?

**Comment by fikrirasyid** [comment] 2016-10-14 01:00
@lots0logs replied at https://github.com/elegantthemes/submodule-builder/pull/1309#discussion_r83343126

**Comment by timayhelen** [comment] 2016-10-15 01:58
@fikrirasyid This isn't the issue I was experiencing:

`Whenever you save a row to the library as a global row, the Background Color changes to a light blue color and you can't update it.`

But, after doing more testing, the issue seems to be isolated to certain rows. Here you can see it happens for one row, and not the other:

![row](https://cloud.githubusercontent.com/assets/3333028/19406704/dd1a5666-923f-11e6-98f6-5f4a6e10187f.gif)

You can download the JSON file here: 
[Divi Builder Layout.json.zip](https://github.com/elegantthemes/Divi-Beta/files/530708/Divi.Builder.Layout.json.zip)

**Comment by fikrirasyid** [comment] 2016-10-15 16:48
@timayhelen thank you for clarifying this issue. I'm currently investigating it now.

**Comment by fikrirasyid** [comment] 2016-10-18 08:37
@timayhelen I've fixed the issue at https://github.com/elegantthemes/submodule-builder/commit/fb4a9ed828fe7801446384d6992d01feb21e93fe. I've explained the issue and the fix on the commit message. I'm copying the explanation here for convenience:

***

The actual issue of the ticket above is global parent incorrectly uses its children attributes. Let's say the given example at https://github.com/elegantthemes/Divi-Beta/issues/623#issuecomment-253955608:

1. CTA module has `background_color` attribute, and it has its value (note: on the issue above, it appears that the CTA module has no background color because its `use_background_color`  attribute is being set to off.
2. The CTA module is inside row which has `background_color` attribute, but it doesn't have its value defined. 
3. The Row is saved to Divi Library as global module.
4. Once the row is saved into Divi Library, it still looks normal. If you check it on the front end of the page, it'll look normal too. 
5. However, if you refresh (<kbd>cmd</kbd> + <kbd>r</kbd>) the page, you'll see that this row now has unwanted background color.

The same issue will happen on different attribute as long as both attributes exists on the CTA module and the global element.  Thus if you repeat the steps above but you're defining `background_image` on the CTA module, once you save its row to Divi Library as global module
+ save the page + refresh the page, the `background_image` will be incorrectly applied to `row`. If you set the section (instead of row) as global module, the `background_color` will be incorrectly applied to `section`.

It is important to note that this issue doesn't affect the saved shortcode. It actually only affects the rendering mechanism. However, once the attribute is incorrectly applied to the global row / section and it accidentally being saved (global module triggers save mechanism when the modul settings modal is closed among various instances), the incorrect change is saved on the layout shortcode. 

It is also important to note that we previously have attempted to fix this issue, but the previous implementation only works if: 
1. module has `background_color` attribute + has defined value
2. Global row has `background_color` attribute + has defined value

In this scenario, the global row `background_color` wouldn't be overwritten by its module. The issue on this PR occurs when:

1. module has `background_color` attribute + has defined value
2. Global row has `background_color` attribute + has **no** defined value

## Replicating issue
To replicate the issue do the following steps on master and in this PR's branch:

1. Import this layout:
https://github.com/elegantthemes/Divi-Beta/files/530708/Divi.Builder.Layout.json.zip
2. Set the row which has `Just Click And Type` CTA module to global module.

You can try re-do the steps and change the background image or set section as global module instead.

**Comment by Jronk** [comment] 2016-10-21 05:55
@fikrirasyid Please see my comment on the PR. Thanks 😃

**Comment by fikrirasyid** [comment] 2016-10-21 07:55
@Jronk I've incorporated your feedback. I've replied your message at https://github.com/elegantthemes/submodule-builder/pull/1309#discussion_r84433829

**Closed** 2016-10-21 23:43 UTC
Labels: !IMPORTANT, BUG, DESIGN SIGNOFF, QUALITY ASSURED, READY FOR REVIEW
