### ISSUE TITLE
Color Picker Default Palette does not work

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#835] opened 2016-12-10 21:46 UTC
### Problem:

The color picker does not show the Color Picker Default Palette assigned in the theme options.

![capture](https://cloud.githubusercontent.com/assets/20072036/21076404/48c63506-bf3b-11e6-892d-e4b67ee0a726.PNG)
![capture-1](https://cloud.githubusercontent.com/assets/20072036/21076405/49b1eeb0-bf3b-11e6-802b-e4d1a7f852f4.PNG)

**Comment by SlavaET** [comment] 2016-12-12 09:05
Fixed.
This issue appears because VB didn't handle saving of default Page Settings values correctly. 
So, if someone saved a page using VB, then default values for `Color Picker Color Pallete` and `Gutter Width` were saved in Page meta and Builder was thinking these values are not default and they were not updated correctly. 
With my fix VB will follow the same logic of saving Page Settings as BB does. But it won't fix the issue for those who already saved Page in VB and changed the values in ePanel after that. We cannot determine whether the value was saved because of this bug or it was saved on purpose.

Steps to reproduce the issue:
1) Create a new page using VB;
2) Save the Page;
3) Change `Color Picker Color Pallete` in ePanel ( and/or `Gutter Width` in Customizer );
4) Reload page in VB, open Page Settings and check `Color Picker Color Pallete` and `Gutter Width` options. You'll see the previous values not updated ones.

**Closed** 2016-12-13 18:44 UTC
Labels: !IMPORTANT, BUG, DESIGN SIGNOFF, QUALITY ASSURED, READY FOR REVIEW

**Comment by abhi-sharm** [comment] 2016-12-19 18:34
is this fix has been released with latest update or yet to be released ?

**Comment by lots0logs** [comment] 2016-12-19 19:08
This fix is included in the latest released version of Divi :+1:
