### ISSUE TITLE
Adding Spaces

### ISSUE THREAD

**Issue by Augustin56** [elegantthemes/Divi-Beta#76] opened 2016-08-19 01:49 UTC
### Problem:

I was using the Visual Builder and trying to cinche up a list below a line of text.  So, I deleted a line space above it and it looked nice.  I saved it.  Then, when I brought the page up live, it had added an extra line space above the list, rather than take one out.

### Steps To Reproduce:
1.  Open a page with a list.
2.  Edit with Visual Builder.
3.  Delete a blank line between the list and the text above it.
4.  Save it.
5.  Bring the page up live.
6.  Note that instead of deleting the line, it added an extra blank line above the list.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshots**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment] 2016-08-24 11:57
@Augustin56 I cannot reproduce this issue. It works fine and space is removed correctly.
Can you please record the screencast showing the issue? Probably I'm missing a step. Also, please make sure you're on the latest Beta version.
![remove-space](https://cloud.githubusercontent.com/assets/3446682/17929696/f25186a6-6a23-11e6-9a92-c70c24d8a069.gif)

**Comment by timayhelen** [comment] 2016-08-26 09:36
I can't seem to replicate this either, so I am closing this for now. @Augustin56 please reply with more details if you are still able to replicate this on your end.

**Closed by timayhelen** 2016-08-26 09:36 UTC
Labels: BUG, QUESTION
