### ISSUE TITLE
Add Divi Builder Plugin Compatbility

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#325] opened 2016-09-03 22:12 UTC
Broken Things:

- [x] Draggable Padding doesn't work. 
- [x] Fullwidth Portfolios are broken. 
- [x] Page Settings bar loads off-center
- [x] Module Move causes JS error. 
- [x] Section background colors don't render. 
- [x] Modal Snap doesn't work. We probably need to remove it.

CSS Conflicts

- [x] Color Picker buttons are styled incorrectly. 

To Do:

- [x] Update grunt zip tasks and gitignore to take into account the new divi builder CSS file.

**Comment by Jronk** [comment] 2016-09-15 18:06
https://github.com/elegantthemes/divi-builder/issues/535 has been updated. Its using the builder https://github.com/elegantthemes/submodule-builder/issues/1081, and that has merged in https://github.com/elegantthemes/Divi-Beta/issues/371 (PR: https://github.com/elegantthemes/submodule-builder/pull/1118)

**Comment by Jronk** [comment] 2016-09-15 18:07
Note, please test the `grunt build` task in the plugin dir (used to be `grunt zip`)

**Comment by timayhelen** [comment] 2016-10-04 00:06
@Jronk I still get the following error when running grunt build:

![screen shot 2016-10-03 at 5 06 04 pm](https://cloud.githubusercontent.com/assets/3333028/19058388/b8a3af88-898b-11e6-80d6-fbaf2ee25661.png)

We need to generate the file as part of the grunt build task.

**Comment by Jronk** [comment] 2016-10-05 05:39
Active submodule-builder PR for this is now: https://github.com/elegantthemes/submodule-builder/issues/1274

**Comment by Jronk** [comment] 2016-10-05 05:41
@timayhelen running grunt build should work with latest, the build task in grunt will run the production build of the fb, generating the needed file. Running regular `grunt` will also run the production build on fb.

**Comment by timayhelen** [comment] 2016-10-05 23:35
@Jronk It still doesn't work for me. I am using the following branches:

divi-builder: 533-front-end-builder
submodule-builder: 325-add-builder-plugin-support

When I run "grunt builder" in the main divi-builder directory, I get the following error:

```
Running "less:development" (less) task
File ./includes/builder/styles/frontend-builder-plugin-style.css created
>> FileError: '../includes/builder/frontend-builder/assets/css/style.css' wasn't found. Tried - includes/builder/frontend-builder/assets/css/style.css,includes/builder/frontend-builder/assets/css/style.css,../includes/builder/frontend-builder/assets/css/style.css in ./less/visual-builder.less on line 6, column 2:
>> 5 .et_divi_builder #et_builder_outer_content {
>> 6 	@import (less) '../includes/builder/frontend-builder/assets/css/style.css';
>> 7 	@import (less) 'visual-builder-reset.css';
Warning: Error compiling ./less/visual-builder.less Use --force to continue.

Aborted due to warnings.
```

**Comment by timayhelen** [comment] 2016-10-05 23:40
nm my branch had no upstream branch and wasn't pulling. I am testing again now.

**Comment by Jronk** [comment] 2016-10-20 20:17
Ok, here is the current product setups to be tested:

Every product below, uses the same submodule-builder branch: `325-add-builder-plugin-support`

Divi Builder Plugin:
branch: `533-front-end-builder`
PR: https://github.com/elegantthemes/divi-builder/pull/535

Divi:
branch: `325-add-builder-plugin-support`
PR: https://github.com/elegantthemes/Divi/pull/2594

Extra:
branch: `325-add-builder-plugin-support`
PR: https://github.com/elegantthemes/Extra/pull/1495

**Comment by Jronk** [comment] 2016-10-20 20:19
Specific features to test:
- [ ] modal snapping should not function in the divi builder plugin
- [ ] nothing should be weird or different in Extra or Divi
- [ ] all 3 products zip/build grunt tasks have been updated, make sure all those turn out perfect

**Comment by Jronk** [comment] 2016-10-21 20:56
Note: https://github.com/elegantthemes/submodule-builder/pull/1321/files#diff-1d6c49a9d39da2441552d9482864e100R1

**Comment by Jronk** [comment] 2016-10-25 21:01
Everyone can/should delete the:
`/includes/builder/frontend-builder/app/assets` dir

**Comment by Jronk** [comment] 2016-10-25 21:10
Ready for review again

Note that the files found in zip I could not reproduce, and there are existing exclusion rules in the Gruntfile.js compress task, so that should not be occurring, so if I can request a re-check on that please that would be great.

All branches have been updated and have their respective `master` branches merged in, so they should all be up to date: https://github.com/elegantthemes/Divi-Beta/issues/325#issuecomment-255215888

**Closed** 2016-10-25 23:06 UTC
Labels: !IMPORTANT, FEATURE, READY FOR REVIEW
