### ISSUE TITLE
Power User Mode

### ISSUE THREAD

**Issue by andyhqtran** [elegantthemes/Divi-Beta#449] opened 2016-09-12 18:45 UTC
We should add in some features that would benefit Divi power users.

# Visual Builder

#### Page Shortcuts
- [x] Undo: <kbd>Super</kbd> + <kbd>Z</kbd>
- [x] Redo: <kbd>Super</kbd> + <kbd>Shift</kbd> + <kbd>Z</kbd>
- [x] Save Page: <kbd>Super</kbd> + <kbd>S</kbd> - Save your current page. - @fikrirasyid
- [x] Save Page as Draft: <kbd>Super</kbd> + <kbd>Shift</kbd> + <kbd>S</kbd> - Save your current page as draft. - @fikrirasyid
- [x] Toggle Settings Bar: <kbd>T</kbd>
- [x] Exit Visual Builder:  <kbd>Super</kbd> + <kbd>E</kbd> - Does the same thing as pressing the Exit Visual Builder button. - @fikrirasyid
- [x] Exit To Backend Builder:  <kbd>Super</kbd> + <kbd>Shift</kbd> + <kbd>E</kbd> - Go to backend builder of current page. - @fikrirasyid
- [x] Zoom-In Screen: <kbd>Super</kbd> + <kbd>+</kbd> - This will basically cycle through each of the preview modes, going down to the next smallest mode. Zoomed Out > Desktop > Tablet > Smartphone.  - @fikrirasyid
- [x] Zoom-Out Screen: <kbd>Super</kbd> + <kbd>-</kbd> - This will basically cycle through each of the preview modes, going up to the next largest mode. Zoomed Out > Desktop > Tablet  > Smartphone. - @fikrirasyid
- [x] Open Page Settings Modal: <kbd>S</kbd> - @fikrirasyid
- [x] Open History Modal: <kbd>H</kbd> - @fikrirasyid
- [x] Open Portablity Modal: <kbd>P</kbd> - @fikrirasyid
- [x] List All Shortcuts: : <kbd>?</kbd> - This will open a modal that lists all available shortcuts. In the future, this can be used for a more dynamic help system with walkthroughs, hints, etc.   - @fikrirasyid

#### Inline Editor Shortcuts
- [x] Exit Inline Editor: <kbd>Esc</kbd>

##### Module Shortcuts
- [x] Lock Module: <kbd>L</kbd> - @andyhqtran 
- [x] Cut Module: <kbd>Super</kbd> + <kbd>X</kbd> - @fikrirasyid
- [x] Copy Module: <kbd>Super</kbd> + <kbd>C</kbd> - @fikrirasyid
- [x] Paste Module: <kbd>Super</kbd> + <kbd>V</kbd> - @fikrirasyid
- [x] Copy Module Design Settings: <kbd>Alt</kbd> + <kbd>Super</kbd> + <kbd>C</kbd> - Copy's the current module settings, excluding all content elements. - @SlavaET
- [x] Paste Module Design Settings: <kbd>Alt</kbd> + <kbd>Super</kbd> + <kbd>V</kbd> - Pastes copied design settings onto the current module of the same time, replacing all design settings with the copied settings but retaining all content. - @SlavaET
- [x] Disable Module: <kbd>D</kbd> - @andyhqtran 
- [x] Resizing Padding/Margin: <kbd>Shift</kbd> + <kbd>Alt</kbd> - While holding shift+alt, resizing will even both top/bottom or left/right.
- [X] Resizing Padding/Margin: <kbd>Shift</kbd> - while hosting shift, padding changes in 10px increments. 
- [X] Resizing Padding/Margin: <kbd>Alt</kbd> - while hosting alt, padding is limited to the max padding of it's opposite side.
- [x] Copy Module + Drag - <kbd>Alt + Module Move</kbd> - Holding alt while moving a module will copy the module and paste it to the moved location. - @SlavaET
- [x] Change Column Structure <kbd>C</kbd> + <kbd>1</kbd> / <kbd>2</kbd> / <kbd>3</kbd> / <kbd>4</kbd> - changes the column structure of the current row being hovered over, or the parent row of the current module being hovered over. - @fikrirasyid
-  [x] Make Row Fullwidth: <kbd>R</kbd> + <kbd>F</kbd> - Make the current row or parent row that is being hovered over fullwidth.  - @fikrirasyid
- [x] Change Gutter Width: <kbd>G</kbd> + <kbd>1</kbd> / <kbd>2</kbd> / <kbd>3</kbd> / <kbd>4</kbd> - Change the gutter width of the current row or parent row being hovered over. - @fikrirasyid
- [x] Increase Row Padding: <kbd>R</kbd> + <kbd>Arrow Left/Right/Up/Down</kbd> - Arrows keys, when pressed, adjust the padding relevant to the direction pressed. - @fikrirasyid
- [x] Increase Row Padding by 10px:  <kbd>Shift</kbd> + <kbd>R</kbd> + <kbd>Arrow Left/Right/Up/Down</kbd> - Arrows keys, when pressed, adjust the padding relevant to the direction pressed in increments of 10.- @fikrirasyid
- [x] Decrease Row Padding: <kbd>Alt</kbd> + <kbd>R</kbd> + <kbd>Arrow Left/Right/Up/Down</kbd> - Arrows keys, when pressed, adjust the padding relevant to the direction pressed.- @fikrirasyid
- [x] Add New Row: <kbd>R</kbd> + <kbd>1</kbd> / <kbd>2</kbd> / <kbd>3</kbd> / <kbd>4</kbd> - Add a new row of specified column type below the current row or parent row being hovered over. - @fikrirasyid
- [x] Increase Section Padding: <kbd>S</kbd> + <kbd>Arrow Left/Right/Up/Down</kbd> - Arrows keys, when pressed, adjust the padding relevant to the direction pressed. 
- [x] Increase Section Padding by 10px:  <kbd>Shift</kbd> + <kbd>S</kbd> + <kbd>Arrow Left/Right/Up/Down</kbd> - Arrows keys, when pressed, adjust the padding relevant to the direction pressed in increments of 10.
- [x] Decrease Section Padding: <kbd>Alt</kbd> + <kbd>S</kbd> + <kbd>Arrow Left/Right/Up/Down</kbd> - Arrows keys, when pressed, adjust the padding relevant to the direction pressed. 
- [x] Add New Section: <kbd>S</kbd> + <kbd>1</kbd> / <kbd>2</kbd> / <kbd>3</kbd> - Add a new section of specified section type below the current section or parent section being hovered over. 1 = Regular, 2 = Specialty, 3 = Fullwidth. - @fikrirasyid
- [x] Open Module Settings - Double Click on module. - @andyhqtran

##### Modal Shortcuts
- [x] Close: <kbd>ESC</kbd>
- [x] Undo: <kbd>Super</kbd> + <kbd>Z</kbd>
- [x] Redo: <kbd>Super</kbd> + <kbd>Shift</kbd> + <kbd>Z</kbd>
- [x] Save Changes: <kbd>Enter</kbd>
- [x] Switch Tabs - <kbd>Tab</kbd>
- [x] Toggle Modal Expand: <kbd>Super</kbd> + <kbd>Enter</kbd> - @SlavaET
- [x] Toggle Modal Snap: <kbd>Shift</kbd> + <kbd>Tab</kbd> - @SlavaET - Changed <kbd>Super</kbd> to <kbd>Shift</kbd>

#### Page Settings
- [ ] Disable Animations
- [ ] Disable Tooltips
- [ ] Show All Outlines & Buttons

# Backend Builder

#### Page Shortcuts
- [x] Save Page: <kbd>Super</kbd> + <kbd>S</kbd> - Save your current page.
- [x] Save Page as Draft: <kbd>Super</kbd> + <kbd>Shift</kbd> + <kbd>S</kbd> - Save your current page as draft.
- [x] Undo: <kbd>Super</kbd> + <kbd>Z</kbd>
- [x] Redo: <kbd>Super</kbd> + <kbd>Shift</kbd> + <kbd>Z</kbd>
- [x] Open History Modal: <kbd>H</kbd> 
- [x] Open Portablity Modal: <kbd>P</kbd>
- [x] Open Page Settings Modal: <kbd>S</kbd>
- [ ] List All Shortcuts: : <kbd>?</kbd> - This will open a modal that lists all available shortcuts. In the future, this can be used for a more dynamic help system with walkthroughs, hints, etc. 

##### Module Shortcuts
- [x] Cut Module: <kbd>Super</kbd> + <kbd>X</kbd> - @SlavaET
- [x] Copy Module: <kbd>Super</kbd> + <kbd>C</kbd> - @SlavaET
- [x] Paste Module: <kbd>Super</kbd> + <kbd>V</kbd> - @SlavaET
- [x] Copy Module + Drag - <kbd>Alt + Module Move</kbd> - Holding alt while moving a module will copy the module and paste it to the moved location. - @SlavaET
- [x] Disable Module: <kbd>D</kbd> - @SlavaET
- [x] Lock Module: <kbd>L</kbd> - @SlavaET
- [x] Change Column Structure <kbd>C</kbd> + <kbd>1</kbd> / <kbd>2</kbd> / <kbd>3</kbd> / <kbd>4</kbd> - changes the column structure of the current row being hovered over, or the parent row of the current module being hovered over.  - @SlavaET
- [x] Add New Row: <kbd>R</kbd> + <kbd>1</kbd> / <kbd>2</kbd> / <kbd>3</kbd> / <kbd>4</kbd> - Add a new row of specified column type below the current row or parent row being hovered over.  - @SlavaET
- [x] Add New Section: <kbd>S</kbd> + <kbd>1</kbd> / <kbd>2</kbd> / <kbd>3</kbd> - Add a new section of specified section type below the current section or parent section being hovered over. 1 = Regular, 2 = Specialty, 3 = Fullwidth.  - @SlavaET
- [x] Open Module Settings - Double Click on module.  - @SlavaET

##### Modal Shortcuts
- [x] Close: <kbd>ESC</kbd>
- [x] Save Changes: <kbd>Enter</kbd>
- [x] Switch Tabs - <kbd>Tab</kbd> - @SlavaET
- [x] Preview Module - <kbd>Super</kbd> + <kbd>P</kbd>- @SlavaET

Also, we need to remember to re-enable the Help modal, which is currently disabled in master since the list of keyboard shortcuts was under development

- [x] Re-enable Help modal after all shortcuts are finished, and make sure all shortcuts are listed and correct.

**Comment by lots0logs** [comment] 2016-09-12 21:41
Related: #433

**Comment by lots0logs** [comment] 2016-09-12 21:44
@andyhqtran :yuno: use these? <kbd>Super</kbd>+<kbd>Z</kbd> lol :wink:

**Comment by andyhqtran** [comment] 2016-09-12 21:46
@lots0logs oh forgot about that feature!

**Comment by timayhelen** [comment] 2016-09-19 20:46
We should also add relevant hotkeys to the BB, such as cut/copy/paste/alt+drag etc.

**Comment by andyhqtran** [comment] 2016-09-26 21:50
@timayhelen modal tabs is taken care of in #1233

**Comment by timayhelen** [comment] 2016-09-27 17:59
@andyhqtran We should add the following shortcuts to Tooltip Modals as well:

- [ ] Tab - change tabs. 
- [ ] Esc - close tooltip.

**Comment by SlavaET** [comment] 2016-09-29 10:14
I'm going to work on `Page Shortcuts` and `Inline Editor Shortcuts`

**Comment by fikrirasyid** [comment] 2016-09-29 17:03
Added the following shortcuts at https://github.com/elegantthemes/submodule-builder/pull/1255:

- [x] Save Page: <kbd>Super</kbd> + <kbd>S</kbd> - Save your current page
- [x] Save Page as Draft: <kbd>Super</kbd> + <kbd>Shift</kbd> + <kbd>S</kbd> - Save your current page as draft
- [x] Open Page Settings Modal: <kbd>S</kbd>
- [x] Open History Modal: <kbd>H</kbd>
- [x] Open Portablity Modal: <kbd>P</kbd>

**Comment by andyhqtran** [comment] 2016-09-29 17:32
@SlavaET can you take care of the <kbd>Tab</kbd> and <kbd>ESC</kbd> for Tooltip Modals? I'm not familiar with how to component was built.

**Comment by timayhelen** [comment] 2016-09-29 18:54
@fikrirasyid @SlavaET @andyhqtran Just a reminder that we should be adding relevant keyboard shortcuts to the BB as well.

**Comment by fikrirasyid** [comment] 2016-09-29 23:42
@timayhelen ah, thank you for bringing that up 👍

**Comment by Jronk** [comment] 2016-09-29 23:58
Also we need to create a help screen/modal that shows all the possible shortcuts

![screen shot 2016-09-29 at 4 58 04 pm](https://cloud.githubusercontent.com/assets/1163441/18976327/f3fa6bc2-8665-11e6-9e77-6dda8086ab68.png)

![screen shot 2016-09-29 at 4 58 16 pm](https://cloud.githubusercontent.com/assets/1163441/18976330/f87c638a-8665-11e6-9445-d124111d91ed.png)

**Comment by timayhelen** [comment] 2016-09-29 23:59
@Jronk It's on the list:

>  List All Shortcuts: : ? - This will open a modal that lists all available shortcuts. In the future, this can be used for a more dynamic help system with walkthroughs, hints, etc.

**Comment by Jronk** [comment] 2016-09-30 00:00
Just noticed, I was about to delete my comment... :facepalm:

**Comment by fikrirasyid** [comment] 2016-09-30 01:05
I think BB will need a preview shortcut :thinking_face:

**Comment by fikrirasyid** [comment] 2016-09-30 01:23
@timayhelen I kinda wonder about <kbd>super</kbd> + <kbd>r</kbd>. Isn't it what browser behaviour does? Default behaviour of <kbd>super</kbd> + <kbd>r</kbd> in all browser, it triggers page reload/refresh which basically does what we'd like to achieve (Will reload the app and clear any unsaved changes.)

**Comment by timayhelen** [comment] 2016-09-30 01:31
@fikrirasyid Yeah Andy added that one, I am not sure if there are advantages to reloading the app and not reloading the page. Let's skip it for now.

**Comment by fikrirasyid** [comment] 2016-09-30 01:49
@timayhelen @andyhqtran noted. I'll skip super + r for now. There's one thing I'd like to discuss tho, I think we need to add an "alias" for <kbd>super</kbd> + <kbd>+</kbd> due to how most keyboard layout are. This is <kbd>+</kbd> button position on most macbooks (my windows keyboard's layout for <kbd>+</kbd> looks like this too)

![img_4900](https://cloud.githubusercontent.com/assets/916442/18978042/a1fa4be2-86e9-11e6-9a64-10977587f6fe.JPG)

Well unless you have this full layout keyboard which has dedicated <kbd>+</kbd> and <kbd>-</kbd> button:

![img_2415](https://cloud.githubusercontent.com/assets/916442/18978050/b27d711a-86e9-11e6-864a-40693f1767c9.JPG)

With this in mind, I think we need to make an alias. Basically <kbd>super</kbd> + <kbd>=</kbd>  is equal to <kbd>super</kbd> + <kbd>+</kbd>. This is what browsers does too. <kbd>super</kbd> + <kbd>=</kbd> triggers zoom in as <kbd>super</kbd> + <kbd>+</kbd> does.

**Comment by timayhelen** [comment] 2016-09-30 03:16
@fikrirasyid Sure that sounds fine. We can create aliases for all keys that have multiple uses.

**Comment by fikrirasyid** [comment] 2016-09-30 03:37
@timayhelen noted, I've added the aliases. Anyway, I think we need to rethink shortcut for quitting VB. There are two reasons:

1. <kbd>super</kbd> + <kbd>q</kbd> is shortcut for quitting browser. If something occurs and the shortcut doesn't kicks in, we'll end up quitting user's browser and I can imagine the rage right now (for user who open tons of tabs, this would be really enraging)
2. Overriding <kbd>super</kbd> + <kbd>q</kbd> browser isn't as simple as overriding other browser shortcut. If you're activating Chrome's warning before quitting (the one that makes you longpress <kbd>super</kbd> + <kbd>q</kbd> before it actually quits), <kbd>super</kbd> + <kbd>q</kbd> doesn't get override.

I think we need something safer. Probably <kbd>super</kbd> + <kbd>e</kbd>.

One more thing: I think we'll need `Exit to backend builder` shortcut as well.

**Comment by timayhelen** [comment] 2016-09-30 04:26
@fikrirasyid ok, sounds good.

**Comment by SlavaET** [comment] 2016-09-30 06:54
Added support of <kbd>Tab</kbd> and <kbd>ESC</kbd> for Tooltip Modals. 
<kbd>ESC</kbd> - closes modal

If modal has tabs:
<kbd>Tab</kbd> - cycles through the modal tabs.

If Change Structure modal opened:
<kbd>Tab</kbd> - cycles forward through the Row Layouts.
<kbd>Shift</kbd> + <kbd>Tab</kbd> - cycles backward through the Row Layouts.

**Comment by SlavaET** [comment] 2016-09-30 10:28
Added following shortcuts: 
- Toggle Modal Expand: <kbd>Super</kbd> + <kbd>Enter</kbd>
- Toggle Modal Snap: <kbd>Shift</kbd> + <kbd>Tab</kbd>

It's not possible to use the <kbd>Super</kbd> + <kbd>Tab</kbd> because this combination is used by system to cycle through opened apps on mac, <kbd>Alt</kbd> + <kbd>Tab</kbd> is a system combination on Windows, <kbd>Ctrl</kbd> + <kbd>Tab</kbd> is a browser combination to cycle through the opened tabs.
The only free combination is <kbd>Shift</kbd> + <kbd>Tab</kbd>, though it might be a little confusing because usually this combination does the same thing as <kbd>Tab</kbd> but in reverse order.

@timayhelen please let me know if we need to use something different there.

**Comment by fikrirasyid** [comment] 2016-09-30 13:51
Added following BB shortcuts:

- Save as draft
- Publish
- open history
- open portability feature

and following FB shortcuts:

- zoom in and zoom out.
- exiting visual builder (redirecting to actual front end post). 
- exiting visual builder to backend builder
- help modal & its shortcut

at https://github.com/elegantthemes/submodule-builder/pull/1259. Let me know if there are things that need to be adjusted.

**Comment by fikrirasyid** [comment] 2016-09-30 14:18
Note: I tested how the shortcode performs on other keyboard layout such as Dvorak, and it appears that the same character uses the same keyCode even when its location changes. Thus, all of our shortcuts are safe 👌

**Comment by timayhelen** [comment] 2016-09-30 18:48
@SlavaET I get the follow error in the branch from modal snap / expand when attempting to close a modal. When I open a modal and then click the green check mark, the following error occurs:

![screen shot 2016-09-30 at 11 47 27 am](https://cloud.githubusercontent.com/assets/3333028/19003021/c36d1114-8703-11e6-8d12-54fa2f1c0309.png)

**Comment by timayhelen** [comment] 2016-09-30 18:49
@fikrirasyid I think we need to add an alias for (?). It only works for me when I do Shift + / (which is how the ? character is usually created). So I guess we need to use "/" to trigger this as well.

**Comment by fikrirasyid** [comment] 2016-09-30 22:16
@timayhelen I've added <kbd>/</kbd> shortcut as alias for toggling help: https://github.com/elegantthemes/submodule-builder/commit/1520ae9a6e0b34717466bb8b0d7308553299546f

**Comment by fikrirasyid** [comment] 2016-09-30 22:26
Anyway, I think the following will make a very useful shortcut:

- Shortcut for switching text color (dark or light). Suggestion: hovered + <kbd>c</kbd> + (<kbd>1</kbd> / <kbd>2</kbd>) (p for 
- Shortcut for switching text alignment (left, center, right, justified). Suggestion: hovered <kbd>+</kbd> + (<kbd>1</kbd> / <kbd>2</kbd> / <kbd>3</kbd> / <kbd>4</kbd> )

When I make a layout, I found these two options are the most frequent thing I accessed on the modal box. Another options that I found I accessed frequently are background and text color. However I'm not sure whether these two are shortcut material since it needs a UI somehow.

**Comment by timayhelen** [comment] 2016-10-01 01:41
@fikrirasyid In the Help modal, we need to replace "super" with the relevant key. "cmd" for OSX and "ctrl" for everything else.

**Comment by timayhelen** [comment] 2016-10-01 02:00
@fikrirasyid When the Help modal is opened, any other modal or tooltip that is currently open should close.

**Comment by timayhelen** [comment] 2016-10-01 03:23
@fikrirasyid We also need to make sure the Enter and Esc work for closing the ? menu.

**Comment by fikrirasyid** [comment] 2016-10-01 04:03
@timayhelen noted. I was thinking the same thing actually, few people on the Facebook Groups asked what <kbd>super</kbd> is after seeing our existing shortcuts list.

> When the Help modal is opened, any other modal or tooltip that is currently open should close.

 This is actually has been added. Can you tell me which tooltip / modal that are still opened? I might miss some of them.

> We also need to make sure the Enter and Esc work for closing the ? menu.

Noted. <kbd>esc</kbd> appears to be logical but I kinda wonder where should we put <kbd>enter</kbd>. Help modal doesn't appear to have input / textarea field :thinking_face:

**Comment by fikrirasyid** [comment] 2016-10-01 17:07
@timayhelen I've pushed several updates to https://github.com/elegantthemes/submodule-builder/pull/1259:

- <kbd>Super</kbd> is now automatically converted into <kbd>cmd</kbd> in OSX and <kbd>ctrl</kbd> in other OS
- when help modal is opened pressing <kbd>esc</kbd> or <kbd>enter</kbd> will automatically closed the modal
- added shortcut alias <kbd>/</kbd> for opening help 
- added copy, cut, and paste shortcut

I'm still working on copy/cut and pasting to empty column / row / section. The way it works is kinda different because there is no clicked to target destination.

**Comment by timayhelen** [comment] 2016-10-01 17:09
Just realized we need to implement Ctrl + Y for redo as well, which is standard on Windows.

**Comment by fikrirasyid** [comment] 2016-10-04 00:09
@timayhelen I've added <kbd>ctrl</kbd> + <kbd>y</kbd> shortcut for redo at https://github.com/elegantthemes/submodule-builder/commit/1ba781b24acf47aa9745c17ac28a92d7339caae6

**Comment by timayhelen** [comment] 2016-10-04 03:46
I had a new idea for a keyboard shortcut, but it might be complicated. However, I know that we already did the work to separate module settings when we created the role editor. SO maybe there is a way to use this separation to decide which is "content" and what is "design."

- [ ] Copy Module Design Settings: <kbd>Alt</kbd> + <kbd>Super</kbd> + <kbd>C</kbd> - Copy's the current module settings, excluding all content elements. 
- [ ] Paste Module Design Settings: <kbd>Alt</kbd> + <kbd>Super</kbd> + <kbd>V</kbd> - Pastes copied design settings onto the current module of the same time, replacing all design settings with the copied settings but retaining all content.

**Comment by fikrirasyid** [comment] 2016-10-04 03:51
@timayhelen I think it will be really helpful. I published an about me page using VB and this is what I repetitively does with several item that has similar styling (see: https://fikrirasyid.com/about/). However, if we added it as shortcut, I think it'd be a good idea to add it on right click options as well.

It is similar to `Paste Style` option in various desktop app (which is really useful)

**Comment by SlavaET** [comment] 2016-10-04 04:58
@timayhelen We already have a mechanism to split the content and design settings in Visual Builder. There is no such mechanism in the BB though and options separation relies on UI, i.e. we can only get design settings when module settings modal is opened.
So adding feature to copy styles will be relatively easy in VB, but for BB it will require some more work to implement this mechanism.
I'll take that one after I finish with the <kbd> Alt </kbd> + Drag shortcut.

**Comment by timayhelen** [comment] 2016-10-04 09:10
@SlavaET Ok, I think it's most useful in the VB anyway.

**Comment by fikrirasyid** [comment] 2016-10-04 09:13
@SlavaET I'm not really sure how you'll implement the copy and paste mechanism, but I'm currently working on polishing copy / cut / paste at `449-add-power-user-features-2` (still working on pasting on empty column / row which apparently can't 100% reuse what's added on right click options). You might be able to reuse some mechanism on that branch.

**Comment by timayhelen** [comment] 2016-10-04 09:21
Also "Paste Style" on right click should only appear if you have copied a style from the same module.

**Comment by fikrirasyid** [comment] 2016-10-04 17:00
@timayhelen I've fixed the copy and paste to empty column / section issue. The fix and the thorough explanation can be seen at:

- https://github.com/elegantthemes/submodule-builder/pull/1259/commits/84e766af863119c7ee63023ff438eb245a2d9f6a
- https://github.com/elegantthemes/submodule-builder/pull/1259/commits/063e8bc7bc1fd94c978adaa8f32388beefea6761

While working on this issue I noticed that in some cases `cut` becomes inconsistent and buggy. I'm currently working on it.

**Comment by fikrirasyid** [comment] 2016-10-05 04:08
@timayhelen https://github.com/elegantthemes/submodule-builder/pull/1259 is ready to be merged. What it does are:

Added following BB shortcuts:

- Save as draft
- Publish
- open history
- open portability feature

Added following FB shortcuts:

- zoom in and zoom out. Note: once it reaches the top or bottom zoom mode, it stops there instead of starting over from the beginning / end preview mode
- exiting visual builder (redirecting to actual front end post). Note: the shortcut is `cmd` + `e`. See: https://github.com/elegantthemes/Divi-Beta/issues/449#issuecomment-250651178
- exiting visual builder to backend builder
- help modal & its shortcut. Note: the UI of the help modal is still work in progress as the final design of the modal hasn't been fixed yet.
- cut, copy, & paste module

***

Note: I recently merged `master` to the PR to fix some merge conflict. It turns out that master has this `escape` issue (see: https://github.com/elegantthemes/Divi-Beta/issues/577) so in some cases this issue appears on the PR as well. I think we should fix https://github.com/elegantthemes/Divi-Beta/issues/577 on different PR. I'm working on it.

**Comment by SlavaET** [comment] 2016-10-05 04:56
Added <kbd>Alt</kbd> + Drag shortcut. It actually <kbd>Alt</kbd> + Drop, since it's the way sortable script works - you need to move something to the new place and then perform the action when drag is finished. so you can start dragging module and then press Alt while you drop module and it'll be copied and will appear in original location + new location. 
Added this shortcut to both BB and VB
https://github.com/elegantthemes/submodule-builder/issues/1272

**Comment by SlavaET** [comment] 2016-10-05 06:41
Added Copy/Paste module styles feature in this PR - https://github.com/elegantthemes/submodule-builder/pull/1275
It works from the Right Click menu only, I will add the respective shortcuts when the following PR will be merged into master - https://github.com/elegantthemes/submodule-builder/pull/1259
because I need the mechanism to get the hovered module which Fikri added in his PR.

**Comment by timayhelen** [comment] 2016-10-05 16:04
@fikrirasyid Ah yeah I guess we should do 1-11. I was only thinking about the first 4 for some reason.

**Comment by fikrirasyid** [comment] 2016-10-05 16:13
@timayhelen alright, noted. Btw, If we're going to do 1 -11, the issue is there's no 1 - 11 on the keyboard:

![img_8896](https://cloud.githubusercontent.com/assets/916442/19121458/ca2a46b0-8b50-11e6-9376-f99bed348f38.JPG)

So, the closest thing we have is <kbd>1</kbd> ~ <kbd>0</kbd> and <kbd>-</kbd> button. What do you think?

**Comment by timayhelen** [comment] 2016-10-05 16:52
@fikrirasyid yeah that makes sense.

**Comment by timayhelen** [comment] 2016-10-06 09:09
@SlavaET Can we make it so that Esc also exits from editing inline text areas that don't launch the Inline Editor, such as Blurb Titles?

**Comment by SlavaET** [comment] 2016-10-06 11:51
Yes, <kbd>Enter</kbd> already does it, so it will be simple to add Esc.

**Comment by SlavaET** [comment] 2016-10-06 16:57
@timayhelen added Esc shortcut for the editable textblocks - https://github.com/elegantthemes/submodule-builder/issues/1286

**Comment by fikrirasyid** [comment] 2016-10-08 15:35
I've submitted PR for remaining module shortcuts at https://github.com/elegantthemes/submodule-builder/pull/1292.

**Comment by timayhelen** [comment] 2016-10-18 23:08
@fikrirasyid Can you add the "?" modal to the backend builder as well? We should trigger the normal BB modal (the large one) and list all of the hotkeys in a similar style to the VB.

**Comment by fikrirasyid** [comment] 2016-10-18 23:11
@timayhelen sure. How about the help modal that is currently being worked tho? If I recall correctly @andyhqtran is currently significantly improving it. I assume we're using the keyboard shortcut layout only on BB and the improved one on FB?

**Closed** 2016-10-18 23:54 UTC
Labels: IMPROVEMENT
