### ISSUE TITLE
Blog module :: show content 

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#609] opened 2016-10-08 09:31 UTC
### Problem:

The shortcodes are removed from the post content in the blog module when show content option enabled. 

### Steps To Reproduce:
1.  Enable Divi builder on post and add modules 
2.  Create a page with blog module and enable show content

Post content
![screenshot_1](https://cloud.githubusercontent.com/assets/9657712/19212071/af0b55fa-8d6b-11e6-90ef-714219e29485.png)

Blog module 
![screenshot_2](https://cloud.githubusercontent.com/assets/9657712/19212079/bb812558-8d6b-11e6-9270-d28aab2c1fb9.png)

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by Anny85** [comment] 2016-10-09 16:47
Duplicate of https://github.com/elegantthemes/Divi-Beta/issues/586

**Closed by Anny85** 2016-10-09 16:47 UTC
