### ISSUE TITLE
Pre-loader Animation Is Off Center

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#460] opened 2016-09-14 00:02 UTC
This used to be centered vertically and horizontally inside the tooltip, but now the vertical positioning is off.

**Comment by timayhelen** [comment] 2016-09-19 20:15
@SlavaET The preloader is still off-center for me in most locations. Here is the Load Layout tooltip:

![screen shot 2016-09-19 at 1 14 52 pm](https://cloud.githubusercontent.com/assets/3333028/18647492/21abb074-7e6b-11e6-8441-6a0149a05842.png)

**Comment by SlavaET** [comment] 2016-09-22 09:20
@timayhelen fixed that one.
Can you please specify where else you see the issue? I checked all the tooltips and preloader looks centered to me with my PR

**Comment by timayhelen** [comment] 2016-09-22 18:59
I get the following warning when loading the VB in this branch. I don't get it in master. I am not sure if it's related to changes in this branch, or perhaps it's because the branch is behind master and this warning was already fixed:

![screen shot 2016-09-22 at 11 58 31 am](https://cloud.githubusercontent.com/assets/3333028/18762009/0a362138-80bc-11e6-8ef0-7613003d7400.png)

**Comment by SlavaET** [comment] 2016-09-23 02:45
@timayhelen I cannot reproduce the error, but I merged the latest master into my branch. Please check it now. Also, try restarting `npm` just in case.

**Comment by timayhelen** [comment] 2016-09-23 18:46
@SlavaET I notice that in this PR, the search input and "replace existing content" text is displayed above the preloader. I think it looked much nicer when these elements were hidden during pre-load. This way the entire tooltip has a white BG and the preloader is centered within it. It doesn't really make sense to show the search bar while it is unusable anyway.

**Comment by SlavaET** [comment] 2016-09-23 20:05
Fixed.

**Comment by timayhelen** [comment] 2016-09-23 20:52
@SlavaET Can we do the same thing for the Add From Library tabs when adding new modules/rows/sections? With the current implementation he preloader sites below the search bar, and it also gets pushed down ad layouts load:

![row-add](https://cloud.githubusercontent.com/assets/3333028/18800987/01573bc2-8195-11e6-856d-d8c70dd2d224.gif)

**Comment by SlavaET** [comment] 2016-09-26 06:16
Done.

**Comment by lots0logs** [comment] 2016-09-27 03:14
This one is proving difficult for me to test because on my server I only get to see the preloader for 1 second if I am lucky. That being said, it doesnt appear to be centered vertically (it is noticeably lower than it should be). Also, the search box and "replace existing content" text are still visible while the preloader is visible.

**Comment by SlavaET** [comment] 2016-09-27 03:40
@lots0logs can you please record a screencast? It looks fine for me and search box with "replace existing content" text are covered by preloader..
Please make sure you cleared cache before testing.

**Comment by lots0logs** [comment] 2016-09-27 04:14
@SlavaET I double and triple checked that it isnt cache issue :grimacing: 

![anim2](https://cloud.githubusercontent.com/assets/4675662/18860029/ee6eafd4-843e-11e6-8db0-49c50bf3431c.gif)

**Comment by timayhelen** [comment] 2016-09-27 05:08
@SlavaET It looks like the initial preloader works, but there appears to be a second preloader that gets pushed down as library items are loaded in. 

![preloader](https://cloud.githubusercontent.com/assets/3333028/18860858/be720d5c-8435-11e6-87b2-73d6a4100464.gif)

**Comment by SlavaET** [comment] 2016-09-27 06:08
Fixed. It should be fine now.

**Closed** 2016-09-27 18:27 UTC
Labels: BUG, DEV SIGNOFF, READY FOR REVIEW
