### ISSUE TITLE
Fullwidth Header Module icon settings disappear behind menu

### ISSUE THREAD

**Issue by VirtualVisionary** [elegantthemes/Divi-Beta#185] opened 2016-08-24 14:41 UTC
### Problem:

When I click on my FW header image, the green border shows up with the icons showing in the upper left corner. But the icons appear behind the primary menu, so when I try to click on the icon, the icons disappear, and it ends up clicking on my logo. When I scroll down the page, which makes the menu shrink, the icons do not show up on the screen where I am. I have to scroll back up to the very top of the page where the menu enlarges again and I cannot click on the FW header module icon settings. (I was trying to change out the picture from the visual editor.) 

### Steps To Reproduce:
1.  From homepage that shows a FW header module and a menu with a partially transparent background color, click or hover on the image. Green border and settings icons appear in upper left corner.
2. Move mouse to settings icons
3. Icons and border disappears and I can only click on the logo
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Toshiba Satellite laptop

**Operating System**: Win10

**Browser**: Firefox 48

**Screen Resolution**: 1080

**Screenshot or Screencast**:
![fw header module   ##issue](https://cloud.githubusercontent.com/assets/21133555/17934687/d38c0d8c-69e6-11e6-8fa8-1b5049168c74.png)

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by fikrirasyid** [comment] 2016-08-24 15:09
@VirtualVisionary thank you for reporting this issue. It seems that this is duplicate of https://github.com/elegantthemes/Divi-Beta/issues/83, so I'm closing it now. We're currently working for a fix for this issue.

**Closed by fikrirasyid** 2016-08-24 15:09 UTC
