### ISSUE TITLE
If Settings and Save to library modals are open they break

### ISSUE THREAD

**Issue by mskol6** [elegantthemes/Divi-Beta#68] opened 2016-08-19 01:03 UTC
### Problem:

When you have the settings modal and the Save to library modal open you can no longer use the close button in the save to library modal. Both modals break. 

### Steps To Reproduce:
1. Open any settings modal
2. Open another save to library modal 
3. Try and close the save to library modal 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: iMac 

**Operating System**: OSX 10.11

**Browser**: Chrome 52

**Screenshots**:

![doublemodalbreak](https://cloud.githubusercontent.com/assets/3596628/17795522/e79ea97e-656d-11e6-8e6f-594370799f27.gif)

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment] 2016-08-19 03:45
duplicate of https://github.com/elegantthemes/Divi-Beta/issues/48

**Closed** 2016-08-19 04:25 UTC
Labels: BUG
