### ISSUE TITLE
Color Palette Initial load is only dark/greys

### ISSUE THREAD

**Issue by SheriLossing** [elegantthemes/Divi-Beta#21] opened 2016-03-24 00:28 UTC
### Problem:

The initial load screen for the Color Palette only shows the blacks. This is confusing, as when you use a color palette it normally shows the full-color palette image. This image does come up once you type a color into the input box, though. Cool feature, but perhaps the initial image should be the full-colored one? See screenshots.

### Steps To Reproduce:
1.
2.
3.
4.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: iMac (Retina 5K, 27-inch, Late 2015)
**Operating System**: OS X El Captain (van.10.11.3)
**Browser**: Chrome
**Screen Resolution**: Retina 5K
**Screenshots**: 
![screen-shot-initial](https://cloud.githubusercontent.com/assets/18037922/14005076/c1f64f58-f135-11e5-8368-0d720a0a1f32.jpg)
![screen-shot-typed-in](https://cloud.githubusercontent.com/assets/18037922/14005079/c7206a7c-f135-11e5-90b5-04086c4a534e.jpg)

-

#### Before submitting your issue, please ensure the following:

- [ ] You searched this Github repo for the issue and found no open reports of the issue.
- [ ] You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
- [ ] You have provided a detailed description of the issue.
- [ ] You have provided any/all relevant information: screenshot, screencast, page URL.
- [ ] You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment] 2016-03-24 01:15
Thanks for the report. Looks like this is a duplicate of: https://github.com/elegantthemes/Divi-Beta/issues/20

**Closed by timayhelen** 2016-03-24 01:15 UTC
