### ISSUE TITLE
Custom CSS :: <br/> added to the code

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#666] opened 2016-10-22 10:47 UTC
### Steps To Reproduce:
1.  Create a new section in VB
2. Add more than one css property and press "enter"after each line
```
content:'test';
background:red;
font-size:20px;
```
3. Save and close VB
4. Open BB and check the css code
![screenshot_11](https://cloud.githubusercontent.com/assets/9657712/19618822/e0e7c9e4-9876-11e6-918a-e027dea10165.png)
![screenshot_10](https://cloud.githubusercontent.com/assets/9657712/19618830/2d61ff92-9877-11e6-965b-fcea13fdf5dc.png)

**Comment by lots0logs** [comment] 2016-10-22 22:21
Duplicate of elegantthemes/Divi#2110

**Comment by lots0logs** [comment] 2016-10-24 18:04
@SlavaET This issue was originally discovered in the BB. I can still reproduce the issue there.

**Comment by timayhelen** [comment] 2016-10-24 21:38
@SlavaET Dustin and I did some testing, and we think that the br's being added in the BB may be due to different line break characters being used on different operating systems. Dustin, running Linux, get's br's added to custom CSS while I don't (working on the same site with the same browser). Can you look into it?

**Comment by SlavaET** [comment] 2016-10-25 05:20
@timayhelen @lots0logs I extended the pattern we use to find the New Line characters in strings and now it should be handled properly for different OS.
Also, I checked the case when it wasn't saved correctly for child elements. Turned out Divi didn't process the New Line characters for such items at all ( in BB only ), I fixed that case in my PR as well.

**Closed** 2016-10-25 19:25 UTC
Labels: !IMPORTANT, BUG, DESIGN SIGNOFF, QUALITY ASSURED, READY FOR REVIEW
