### ISSUE TITLE
Bar Counters :: Incorrect List Style

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#983] opened 2017-02-15 18:11 UTC
### Problem:

![2017-02-15_12-09-27-pm](https://cloud.githubusercontent.com/assets/4675662/22988442/b9471d48-f377-11e6-9c72-4ab898d81da1.png)

**Comment by lceberg** [comment] 2017-02-16 10:30
@lots0logs Are there any specific steps to reproduce this ?

This is what I see on latest mater:

#### About Us Layout:
![about-us](https://cloud.githubusercontent.com/assets/1928328/23017607/a07fe1e2-f443-11e6-873b-907bbb121749.png)

#### Single Bar Counter:
![single-module](https://cloud.githubusercontent.com/assets/1928328/23017613/a60a3cf2-f443-11e6-9f81-3fa78132a67f.png)

**Comment by timayhelen** [comment] 2017-02-16 10:46
@lceberg This was caused by your recent UL adjustments, which affected many modules. I reversed the fix in the latest master and applied a less aggressive adjustment instead, so we can close this issue.

**Closed by timayhelen** 2017-02-16 10:46 UTC
Labels: BUG, QUESTION
