### ISSUE TITLE
"Add Row" and "Add Section" Buttons Overlapping with Minimal/No Row Margin/Padding

### ISSUE THREAD

**Issue by coreykcreech** [elegantthemes/Divi-Beta#143] opened 2016-08-20 18:28 UTC
### Problem:

When editing with the visual editor, if you have a row that ends a section and contains no padding/margin, the "Add Row" and "Add Section" buttons overlap.

Working in Chrome v.52.0.2743.116 m on Desktop, 1920x1080.

### Steps To Reproduce:
1.  
2. 
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: PC

**Operating System**: Win 10

**Browser**: Chrome v.52.0.2743.116 m

**Screen Resolution**: 1920x1080

**Screenshot or Screencast**: http://dev.coreykcreech.com/wp-content/uploads/2016/08/Add-Row-and-Add-Section-Overlapping.png

**Link To Download Layout JSON File**: 

http://dev.coreykcreech.com/wp-content/uploads/Beta/Dev-Home.json
  OR 
https://www.dropbox.com/s/i9rbb0oa2a77i08/Dev-Home.json?dl=0

**Comment by eduard-ungureanu** [comment] 2016-08-31 17:50
I think the issue is still present. For example if I have just on row with little content, but add new section button can be accessed without any problems, the problems is when I add more content, and I have to scroll down, then the button that expends the page settings is on top of the Add new section Button, make it very hard to click.

Here is a video recording about this:
https://drive.google.com/file/d/0B8PjD3Z_XQvuMGNndE1DTjgtZ00/view?usp=sharing

Notice that all the rows and the initial section has the default padding.

**Comment by timayhelen** [comment] 2016-09-22 20:01
This has been fixed in master.

**Closed by timayhelen** 2016-09-22 20:01 UTC
Labels: BUG
